-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_LOAD_INPUT is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    m_axi_gmem0_0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    local_input_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_ce0 : OUT STD_LOGIC;
    local_input_we0 : OUT STD_LOGIC;
    local_input_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_1_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_1_ce0 : OUT STD_LOGIC;
    local_input_1_we0 : OUT STD_LOGIC;
    local_input_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_2_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_2_ce0 : OUT STD_LOGIC;
    local_input_2_we0 : OUT STD_LOGIC;
    local_input_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_3_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_3_ce0 : OUT STD_LOGIC;
    local_input_3_we0 : OUT STD_LOGIC;
    local_input_3_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_4_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_4_ce0 : OUT STD_LOGIC;
    local_input_4_we0 : OUT STD_LOGIC;
    local_input_4_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_5_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_5_ce0 : OUT STD_LOGIC;
    local_input_5_we0 : OUT STD_LOGIC;
    local_input_5_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_6_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_6_ce0 : OUT STD_LOGIC;
    local_input_6_we0 : OUT STD_LOGIC;
    local_input_6_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_7_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_7_ce0 : OUT STD_LOGIC;
    local_input_7_we0 : OUT STD_LOGIC;
    local_input_7_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_8_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_8_ce0 : OUT STD_LOGIC;
    local_input_8_we0 : OUT STD_LOGIC;
    local_input_8_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_9_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_9_ce0 : OUT STD_LOGIC;
    local_input_9_we0 : OUT STD_LOGIC;
    local_input_9_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_10_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_10_ce0 : OUT STD_LOGIC;
    local_input_10_we0 : OUT STD_LOGIC;
    local_input_10_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_11_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_11_ce0 : OUT STD_LOGIC;
    local_input_11_we0 : OUT STD_LOGIC;
    local_input_11_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_12_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_12_ce0 : OUT STD_LOGIC;
    local_input_12_we0 : OUT STD_LOGIC;
    local_input_12_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_13_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_13_ce0 : OUT STD_LOGIC;
    local_input_13_we0 : OUT STD_LOGIC;
    local_input_13_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_14_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_14_ce0 : OUT STD_LOGIC;
    local_input_14_we0 : OUT STD_LOGIC;
    local_input_14_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_15_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_15_ce0 : OUT STD_LOGIC;
    local_input_15_we0 : OUT STD_LOGIC;
    local_input_15_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_16_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_16_ce0 : OUT STD_LOGIC;
    local_input_16_we0 : OUT STD_LOGIC;
    local_input_16_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_17_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_17_ce0 : OUT STD_LOGIC;
    local_input_17_we0 : OUT STD_LOGIC;
    local_input_17_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_18_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_18_ce0 : OUT STD_LOGIC;
    local_input_18_we0 : OUT STD_LOGIC;
    local_input_18_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_19_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_19_ce0 : OUT STD_LOGIC;
    local_input_19_we0 : OUT STD_LOGIC;
    local_input_19_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_20_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_20_ce0 : OUT STD_LOGIC;
    local_input_20_we0 : OUT STD_LOGIC;
    local_input_20_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_21_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_21_ce0 : OUT STD_LOGIC;
    local_input_21_we0 : OUT STD_LOGIC;
    local_input_21_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_22_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_22_ce0 : OUT STD_LOGIC;
    local_input_22_we0 : OUT STD_LOGIC;
    local_input_22_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_23_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_23_ce0 : OUT STD_LOGIC;
    local_input_23_we0 : OUT STD_LOGIC;
    local_input_23_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_24_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_24_ce0 : OUT STD_LOGIC;
    local_input_24_we0 : OUT STD_LOGIC;
    local_input_24_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_25_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_25_ce0 : OUT STD_LOGIC;
    local_input_25_we0 : OUT STD_LOGIC;
    local_input_25_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_26_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_26_ce0 : OUT STD_LOGIC;
    local_input_26_we0 : OUT STD_LOGIC;
    local_input_26_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_27_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_27_ce0 : OUT STD_LOGIC;
    local_input_27_we0 : OUT STD_LOGIC;
    local_input_27_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_28_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_28_ce0 : OUT STD_LOGIC;
    local_input_28_we0 : OUT STD_LOGIC;
    local_input_28_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_29_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    local_input_29_ce0 : OUT STD_LOGIC;
    local_input_29_we0 : OUT STD_LOGIC;
    local_input_29_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    sext_ln59 : IN STD_LOGIC_VECTOR (59 downto 0);
    dbg_in0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    dbg_in0_ap_vld : OUT STD_LOGIC );
end;


architecture behav of street_fighter_cnn_street_fighter_cnn_Pipeline_LOAD_INPUT is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv112_0 : STD_LOGIC_VECTOR (111 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv7_78 : STD_LOGIC_VECTOR (6 downto 0) := "1111000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv15_CD : STD_LOGIC_VECTOR (14 downto 0) := "000000011001101";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv7_4 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv11_34 : STD_LOGIC_VECTOR (10 downto 0) := "00000110100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv7_13 : STD_LOGIC_VECTOR (6 downto 0) := "0010011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln59_reg_930 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_934 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op55_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln59_fu_635_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem0_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln59_reg_930_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_fu_651_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_934_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln62_1_reg_938 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln62_3_fu_676_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln62_3_reg_942 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln63_fu_695_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln63_reg_946 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln63_reg_946_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem0_addr_read_reg_950 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_phi_mux_empty_phi_fu_583_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_phi_reg_pp0_iter2_empty_reg_580 : STD_LOGIC_VECTOR (127 downto 0);
    signal zext_ln59_fu_745_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal zext_ln62_fu_822_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal phi_urem45_fu_152 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal select_ln59_fu_713_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_phi_urem45_load : STD_LOGIC_VECTOR (6 downto 0);
    signal phi_urem_fu_156 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal select_ln59_1_fu_871_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal phi_mul_fu_160 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal add_ln62_1_fu_660_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_sig_allocacmp_phi_mul_load : STD_LOGIC_VECTOR (14 downto 0);
    signal shiftreg_fu_164 : STD_LOGIC_VECTOR (111 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal i_fu_168 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln59_fu_641_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (6 downto 0);
    signal val_fu_753_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal local_input_23_we0_local : STD_LOGIC;
    signal ap_predicate_pred486_state3 : BOOLEAN;
    signal local_input_23_ce0_local : STD_LOGIC;
    signal local_input_22_we0_local : STD_LOGIC;
    signal ap_predicate_pred500_state3 : BOOLEAN;
    signal local_input_22_ce0_local : STD_LOGIC;
    signal local_input_21_we0_local : STD_LOGIC;
    signal ap_predicate_pred514_state3 : BOOLEAN;
    signal local_input_21_ce0_local : STD_LOGIC;
    signal local_input_20_we0_local : STD_LOGIC;
    signal ap_predicate_pred527_state3 : BOOLEAN;
    signal local_input_20_ce0_local : STD_LOGIC;
    signal local_input_24_we0_local : STD_LOGIC;
    signal ap_predicate_pred546_state3 : BOOLEAN;
    signal local_input_24_ce0_local : STD_LOGIC;
    signal local_input_18_we0_local : STD_LOGIC;
    signal ap_predicate_pred559_state3 : BOOLEAN;
    signal local_input_18_ce0_local : STD_LOGIC;
    signal local_input_17_we0_local : STD_LOGIC;
    signal ap_predicate_pred571_state3 : BOOLEAN;
    signal local_input_17_ce0_local : STD_LOGIC;
    signal local_input_16_we0_local : STD_LOGIC;
    signal ap_predicate_pred583_state3 : BOOLEAN;
    signal local_input_16_ce0_local : STD_LOGIC;
    signal local_input_15_we0_local : STD_LOGIC;
    signal ap_predicate_pred595_state3 : BOOLEAN;
    signal local_input_15_ce0_local : STD_LOGIC;
    signal local_input_19_we0_local : STD_LOGIC;
    signal ap_predicate_pred610_state3 : BOOLEAN;
    signal local_input_19_ce0_local : STD_LOGIC;
    signal local_input_13_we0_local : STD_LOGIC;
    signal ap_predicate_pred623_state3 : BOOLEAN;
    signal local_input_13_ce0_local : STD_LOGIC;
    signal local_input_12_we0_local : STD_LOGIC;
    signal ap_predicate_pred635_state3 : BOOLEAN;
    signal local_input_12_ce0_local : STD_LOGIC;
    signal local_input_11_we0_local : STD_LOGIC;
    signal ap_predicate_pred647_state3 : BOOLEAN;
    signal local_input_11_ce0_local : STD_LOGIC;
    signal local_input_10_we0_local : STD_LOGIC;
    signal ap_predicate_pred659_state3 : BOOLEAN;
    signal local_input_10_ce0_local : STD_LOGIC;
    signal local_input_14_we0_local : STD_LOGIC;
    signal ap_predicate_pred674_state3 : BOOLEAN;
    signal local_input_14_ce0_local : STD_LOGIC;
    signal local_input_8_we0_local : STD_LOGIC;
    signal ap_predicate_pred687_state3 : BOOLEAN;
    signal local_input_8_ce0_local : STD_LOGIC;
    signal local_input_7_we0_local : STD_LOGIC;
    signal ap_predicate_pred699_state3 : BOOLEAN;
    signal local_input_7_ce0_local : STD_LOGIC;
    signal local_input_6_we0_local : STD_LOGIC;
    signal ap_predicate_pred711_state3 : BOOLEAN;
    signal local_input_6_ce0_local : STD_LOGIC;
    signal local_input_5_we0_local : STD_LOGIC;
    signal ap_predicate_pred723_state3 : BOOLEAN;
    signal local_input_5_ce0_local : STD_LOGIC;
    signal local_input_9_we0_local : STD_LOGIC;
    signal ap_predicate_pred738_state3 : BOOLEAN;
    signal local_input_9_ce0_local : STD_LOGIC;
    signal local_input_3_we0_local : STD_LOGIC;
    signal ap_predicate_pred751_state3 : BOOLEAN;
    signal local_input_3_ce0_local : STD_LOGIC;
    signal local_input_2_we0_local : STD_LOGIC;
    signal ap_predicate_pred763_state3 : BOOLEAN;
    signal local_input_2_ce0_local : STD_LOGIC;
    signal local_input_1_we0_local : STD_LOGIC;
    signal ap_predicate_pred775_state3 : BOOLEAN;
    signal local_input_1_ce0_local : STD_LOGIC;
    signal local_input_we0_local : STD_LOGIC;
    signal ap_predicate_pred787_state3 : BOOLEAN;
    signal local_input_ce0_local : STD_LOGIC;
    signal local_input_4_we0_local : STD_LOGIC;
    signal ap_predicate_pred802_state3 : BOOLEAN;
    signal local_input_4_ce0_local : STD_LOGIC;
    signal local_input_28_we0_local : STD_LOGIC;
    signal ap_predicate_pred823_state3 : BOOLEAN;
    signal local_input_28_ce0_local : STD_LOGIC;
    signal local_input_27_we0_local : STD_LOGIC;
    signal ap_predicate_pred835_state3 : BOOLEAN;
    signal local_input_27_ce0_local : STD_LOGIC;
    signal local_input_26_we0_local : STD_LOGIC;
    signal ap_predicate_pred847_state3 : BOOLEAN;
    signal local_input_26_ce0_local : STD_LOGIC;
    signal local_input_25_we0_local : STD_LOGIC;
    signal ap_predicate_pred859_state3 : BOOLEAN;
    signal local_input_25_ce0_local : STD_LOGIC;
    signal local_input_29_we0_local : STD_LOGIC;
    signal ap_predicate_pred874_state3 : BOOLEAN;
    signal local_input_29_ce0_local : STD_LOGIC;
    signal trunc_ln59_fu_647_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln59_1_fu_707_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln59_1_fu_701_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln62_2_fu_798_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln62_fu_806_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln62_fu_806_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln62_fu_806_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_812_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln59_2_fu_865_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln59_2_fu_859_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln62_fu_806_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component street_fighter_cnn_mul_5ns_7ns_11_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component street_fighter_cnn_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_5ns_7ns_11_1_1_U1 : component street_fighter_cnn_mul_5ns_7ns_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => mul_ln62_fu_806_p0,
        din1 => mul_ln62_fu_806_p1,
        dout => mul_ln62_fu_806_p2);

    flow_control_loop_pipe_sequential_init_U : component street_fighter_cnn_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln59_fu_635_p2 = ap_const_lv1_0))) then 
                    i_fu_168 <= add_ln59_fu_641_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_168 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    phi_mul_fu_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln59_fu_635_p2 = ap_const_lv1_0))) then 
                    phi_mul_fu_160 <= add_ln62_1_fu_660_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    phi_mul_fu_160 <= ap_const_lv15_0;
                end if;
            end if; 
        end if;
    end process;

    phi_urem45_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln59_fu_635_p2 = ap_const_lv1_0))) then 
                    phi_urem45_fu_152 <= select_ln59_fu_713_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    phi_urem45_fu_152 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    phi_urem_fu_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    phi_urem_fu_156 <= ap_const_lv7_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    phi_urem_fu_156 <= select_ln59_1_fu_871_p3;
                end if;
            end if; 
        end if;
    end process;

    shiftreg_fu_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    shiftreg_fu_164 <= ap_const_lv112_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    shiftreg_fu_164 <= ap_phi_mux_empty_phi_fu_583_p4(127 downto 16);
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                    ap_predicate_pred486_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_3) and (trunc_ln62_1_reg_938 = ap_const_lv3_4));
                    ap_predicate_pred500_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_2) and (trunc_ln62_1_reg_938 = ap_const_lv3_4));
                    ap_predicate_pred514_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_1) and (trunc_ln62_1_reg_938 = ap_const_lv3_4));
                    ap_predicate_pred527_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_0) and (trunc_ln62_1_reg_938 = ap_const_lv3_4));
                    ap_predicate_pred546_state3 <= (not((trunc_ln62_3_reg_942 = ap_const_lv3_0)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_1)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_2)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_3)) and (trunc_ln62_1_reg_938 = ap_const_lv3_4));
                    ap_predicate_pred559_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_3) and (trunc_ln62_1_reg_938 = ap_const_lv3_3));
                    ap_predicate_pred571_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_2) and (trunc_ln62_1_reg_938 = ap_const_lv3_3));
                    ap_predicate_pred583_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_1) and (trunc_ln62_1_reg_938 = ap_const_lv3_3));
                    ap_predicate_pred595_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_0) and (trunc_ln62_1_reg_938 = ap_const_lv3_3));
                    ap_predicate_pred610_state3 <= (not((trunc_ln62_3_reg_942 = ap_const_lv3_0)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_1)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_2)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_3)) and (trunc_ln62_1_reg_938 = ap_const_lv3_3));
                    ap_predicate_pred623_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_3) and (trunc_ln62_1_reg_938 = ap_const_lv3_2));
                    ap_predicate_pred635_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_2) and (trunc_ln62_1_reg_938 = ap_const_lv3_2));
                    ap_predicate_pred647_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_1) and (trunc_ln62_1_reg_938 = ap_const_lv3_2));
                    ap_predicate_pred659_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_0) and (trunc_ln62_1_reg_938 = ap_const_lv3_2));
                    ap_predicate_pred674_state3 <= (not((trunc_ln62_3_reg_942 = ap_const_lv3_0)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_1)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_2)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_3)) and (trunc_ln62_1_reg_938 = ap_const_lv3_2));
                    ap_predicate_pred687_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_3) and (trunc_ln62_1_reg_938 = ap_const_lv3_1));
                    ap_predicate_pred699_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_2) and (trunc_ln62_1_reg_938 = ap_const_lv3_1));
                    ap_predicate_pred711_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_1) and (trunc_ln62_1_reg_938 = ap_const_lv3_1));
                    ap_predicate_pred723_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_0) and (trunc_ln62_1_reg_938 = ap_const_lv3_1));
                    ap_predicate_pred738_state3 <= (not((trunc_ln62_3_reg_942 = ap_const_lv3_0)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_1)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_2)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_3)) and (trunc_ln62_1_reg_938 = ap_const_lv3_1));
                    ap_predicate_pred751_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_3) and (trunc_ln62_1_reg_938 = ap_const_lv3_0));
                    ap_predicate_pred763_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_2) and (trunc_ln62_1_reg_938 = ap_const_lv3_0));
                    ap_predicate_pred775_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_1) and (trunc_ln62_1_reg_938 = ap_const_lv3_0));
                    ap_predicate_pred787_state3 <= ((trunc_ln62_3_reg_942 = ap_const_lv3_0) and (trunc_ln62_1_reg_938 = ap_const_lv3_0));
                    ap_predicate_pred802_state3 <= (not((trunc_ln62_3_reg_942 = ap_const_lv3_0)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_1)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_2)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_3)) and (trunc_ln62_1_reg_938 = ap_const_lv3_0));
                    ap_predicate_pred823_state3 <= (not((trunc_ln62_1_reg_938 = ap_const_lv3_0)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_1)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_2)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_3)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_4)) and (trunc_ln62_3_reg_942 = ap_const_lv3_3));
                    ap_predicate_pred835_state3 <= (not((trunc_ln62_1_reg_938 = ap_const_lv3_0)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_1)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_2)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_3)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_4)) and (trunc_ln62_3_reg_942 = ap_const_lv3_2));
                    ap_predicate_pred847_state3 <= (not((trunc_ln62_1_reg_938 = ap_const_lv3_0)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_1)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_2)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_3)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_4)) and (trunc_ln62_3_reg_942 = ap_const_lv3_1));
                    ap_predicate_pred859_state3 <= (not((trunc_ln62_1_reg_938 = ap_const_lv3_0)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_1)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_2)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_3)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_4)) and (trunc_ln62_3_reg_942 = ap_const_lv3_0));
                    ap_predicate_pred874_state3 <= (not((trunc_ln62_1_reg_938 = ap_const_lv3_0)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_1)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_2)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_3)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_0)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_1)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_2)) and not((trunc_ln62_3_reg_942 = ap_const_lv3_3)) and not((trunc_ln62_1_reg_938 = ap_const_lv3_4)));
                gmem0_addr_read_reg_950 <= m_axi_gmem0_0_RDATA;
                icmp_ln59_reg_930 <= icmp_ln59_fu_635_p2;
                icmp_ln59_reg_930_pp0_iter1_reg <= icmp_ln59_reg_930;
                icmp_ln61_reg_934 <= icmp_ln61_fu_651_p2;
                icmp_ln61_reg_934_pp0_iter1_reg <= icmp_ln61_reg_934;
                icmp_ln63_reg_946 <= icmp_ln63_fu_695_p2;
                icmp_ln63_reg_946_pp0_iter1_reg <= icmp_ln63_reg_946;
                trunc_ln62_1_reg_938 <= ap_sig_allocacmp_phi_mul_load(14 downto 12);
                trunc_ln62_3_reg_942 <= trunc_ln62_3_fu_676_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln59_1_fu_701_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_urem45_load) + unsigned(ap_const_lv7_1));
    add_ln59_2_fu_859_p2 <= std_logic_vector(unsigned(phi_urem_fu_156) + unsigned(ap_const_lv7_1));
    add_ln59_fu_641_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv7_1));
    add_ln62_1_fu_660_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_mul_load) + unsigned(ap_const_lv15_CD));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(m_axi_gmem0_0_RVALID, ap_predicate_op55_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((ap_predicate_op55_read_state2 = ap_const_boolean_1) and (m_axi_gmem0_0_RVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln59_fu_635_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln59_fu_635_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_empty_phi_fu_583_p4_assign_proc : process(icmp_ln59_reg_930_pp0_iter1_reg, icmp_ln61_reg_934_pp0_iter1_reg, gmem0_addr_read_reg_950, ap_phi_reg_pp0_iter2_empty_reg_580, zext_ln59_fu_745_p1)
    begin
        if ((icmp_ln59_reg_930_pp0_iter1_reg = ap_const_lv1_0)) then
            if ((icmp_ln61_reg_934_pp0_iter1_reg = ap_const_lv1_0)) then 
                ap_phi_mux_empty_phi_fu_583_p4 <= zext_ln59_fu_745_p1;
            elsif ((icmp_ln61_reg_934_pp0_iter1_reg = ap_const_lv1_1)) then 
                ap_phi_mux_empty_phi_fu_583_p4 <= gmem0_addr_read_reg_950;
            else 
                ap_phi_mux_empty_phi_fu_583_p4 <= ap_phi_reg_pp0_iter2_empty_reg_580;
            end if;
        else 
            ap_phi_mux_empty_phi_fu_583_p4 <= ap_phi_reg_pp0_iter2_empty_reg_580;
        end if; 
    end process;

    ap_phi_reg_pp0_iter2_empty_reg_580 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op55_read_state2_assign_proc : process(icmp_ln59_reg_930, icmp_ln61_reg_934)
    begin
                ap_predicate_op55_read_state2 <= ((icmp_ln61_reg_934 = ap_const_lv1_1) and (icmp_ln59_reg_930 = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_168)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_168;
        end if; 
    end process;


    ap_sig_allocacmp_phi_mul_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, phi_mul_fu_160)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_phi_mul_load <= ap_const_lv15_0;
        else 
            ap_sig_allocacmp_phi_mul_load <= phi_mul_fu_160;
        end if; 
    end process;


    ap_sig_allocacmp_phi_urem45_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, phi_urem45_fu_152, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_phi_urem45_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_phi_urem45_load <= phi_urem45_fu_152;
        end if; 
    end process;

    dbg_in0 <= val_fu_753_p1;

    dbg_in0_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln63_reg_946_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln63_reg_946_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            dbg_in0_ap_vld <= ap_const_logic_1;
        else 
            dbg_in0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    gmem0_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem0_0_RVALID, ap_predicate_op55_read_state2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op55_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem0_blk_n_R <= m_axi_gmem0_0_RVALID;
        else 
            gmem0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln59_1_fu_707_p2 <= "1" when (ap_sig_allocacmp_phi_urem45_load = ap_const_lv7_4) else "0";
    icmp_ln59_2_fu_865_p2 <= "1" when (phi_urem_fu_156 = ap_const_lv7_13) else "0";
    icmp_ln59_fu_635_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv7_78) else "0";
    icmp_ln61_fu_651_p2 <= "1" when (trunc_ln59_fu_647_p1 = ap_const_lv3_0) else "0";
    icmp_ln63_fu_695_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv7_0) else "0";
    local_input_10_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_10_ce0 <= local_input_10_ce0_local;

    local_input_10_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_10_ce0_local <= ap_const_logic_1;
        else 
            local_input_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_10_d0 <= val_fu_753_p1;
    local_input_10_we0 <= local_input_10_we0_local;

    local_input_10_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred659_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred659_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_10_we0_local <= ap_const_logic_1;
        else 
            local_input_10_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_11_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_11_ce0 <= local_input_11_ce0_local;

    local_input_11_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_11_ce0_local <= ap_const_logic_1;
        else 
            local_input_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_11_d0 <= val_fu_753_p1;
    local_input_11_we0 <= local_input_11_we0_local;

    local_input_11_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred647_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred647_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_11_we0_local <= ap_const_logic_1;
        else 
            local_input_11_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_12_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_12_ce0 <= local_input_12_ce0_local;

    local_input_12_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_12_ce0_local <= ap_const_logic_1;
        else 
            local_input_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_12_d0 <= val_fu_753_p1;
    local_input_12_we0 <= local_input_12_we0_local;

    local_input_12_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred635_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred635_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_12_we0_local <= ap_const_logic_1;
        else 
            local_input_12_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_13_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_13_ce0 <= local_input_13_ce0_local;

    local_input_13_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_13_ce0_local <= ap_const_logic_1;
        else 
            local_input_13_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_13_d0 <= val_fu_753_p1;
    local_input_13_we0 <= local_input_13_we0_local;

    local_input_13_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred623_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred623_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_13_we0_local <= ap_const_logic_1;
        else 
            local_input_13_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_14_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_14_ce0 <= local_input_14_ce0_local;

    local_input_14_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_14_ce0_local <= ap_const_logic_1;
        else 
            local_input_14_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_14_d0 <= val_fu_753_p1;
    local_input_14_we0 <= local_input_14_we0_local;

    local_input_14_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred674_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred674_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_14_we0_local <= ap_const_logic_1;
        else 
            local_input_14_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_15_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_15_ce0 <= local_input_15_ce0_local;

    local_input_15_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_15_ce0_local <= ap_const_logic_1;
        else 
            local_input_15_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_15_d0 <= val_fu_753_p1;
    local_input_15_we0 <= local_input_15_we0_local;

    local_input_15_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred595_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred595_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_15_we0_local <= ap_const_logic_1;
        else 
            local_input_15_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_16_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_16_ce0 <= local_input_16_ce0_local;

    local_input_16_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_16_ce0_local <= ap_const_logic_1;
        else 
            local_input_16_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_16_d0 <= val_fu_753_p1;
    local_input_16_we0 <= local_input_16_we0_local;

    local_input_16_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred583_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred583_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_16_we0_local <= ap_const_logic_1;
        else 
            local_input_16_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_17_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_17_ce0 <= local_input_17_ce0_local;

    local_input_17_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_17_ce0_local <= ap_const_logic_1;
        else 
            local_input_17_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_17_d0 <= val_fu_753_p1;
    local_input_17_we0 <= local_input_17_we0_local;

    local_input_17_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred571_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred571_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_17_we0_local <= ap_const_logic_1;
        else 
            local_input_17_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_18_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_18_ce0 <= local_input_18_ce0_local;

    local_input_18_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_18_ce0_local <= ap_const_logic_1;
        else 
            local_input_18_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_18_d0 <= val_fu_753_p1;
    local_input_18_we0 <= local_input_18_we0_local;

    local_input_18_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred559_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred559_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_18_we0_local <= ap_const_logic_1;
        else 
            local_input_18_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_19_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_19_ce0 <= local_input_19_ce0_local;

    local_input_19_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_19_ce0_local <= ap_const_logic_1;
        else 
            local_input_19_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_19_d0 <= val_fu_753_p1;
    local_input_19_we0 <= local_input_19_we0_local;

    local_input_19_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred610_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred610_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_19_we0_local <= ap_const_logic_1;
        else 
            local_input_19_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_1_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_1_ce0 <= local_input_1_ce0_local;

    local_input_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_1_ce0_local <= ap_const_logic_1;
        else 
            local_input_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_1_d0 <= val_fu_753_p1;
    local_input_1_we0 <= local_input_1_we0_local;

    local_input_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred775_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred775_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_1_we0_local <= ap_const_logic_1;
        else 
            local_input_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_20_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_20_ce0 <= local_input_20_ce0_local;

    local_input_20_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_20_ce0_local <= ap_const_logic_1;
        else 
            local_input_20_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_20_d0 <= val_fu_753_p1;
    local_input_20_we0 <= local_input_20_we0_local;

    local_input_20_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred527_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred527_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_20_we0_local <= ap_const_logic_1;
        else 
            local_input_20_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_21_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_21_ce0 <= local_input_21_ce0_local;

    local_input_21_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_21_ce0_local <= ap_const_logic_1;
        else 
            local_input_21_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_21_d0 <= val_fu_753_p1;
    local_input_21_we0 <= local_input_21_we0_local;

    local_input_21_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred514_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred514_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_21_we0_local <= ap_const_logic_1;
        else 
            local_input_21_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_22_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_22_ce0 <= local_input_22_ce0_local;

    local_input_22_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_22_ce0_local <= ap_const_logic_1;
        else 
            local_input_22_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_22_d0 <= val_fu_753_p1;
    local_input_22_we0 <= local_input_22_we0_local;

    local_input_22_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred500_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred500_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_22_we0_local <= ap_const_logic_1;
        else 
            local_input_22_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_23_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_23_ce0 <= local_input_23_ce0_local;

    local_input_23_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_23_ce0_local <= ap_const_logic_1;
        else 
            local_input_23_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_23_d0 <= val_fu_753_p1;
    local_input_23_we0 <= local_input_23_we0_local;

    local_input_23_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred486_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred486_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_23_we0_local <= ap_const_logic_1;
        else 
            local_input_23_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_24_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_24_ce0 <= local_input_24_ce0_local;

    local_input_24_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_24_ce0_local <= ap_const_logic_1;
        else 
            local_input_24_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_24_d0 <= val_fu_753_p1;
    local_input_24_we0 <= local_input_24_we0_local;

    local_input_24_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred546_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred546_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_24_we0_local <= ap_const_logic_1;
        else 
            local_input_24_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_25_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_25_ce0 <= local_input_25_ce0_local;

    local_input_25_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_25_ce0_local <= ap_const_logic_1;
        else 
            local_input_25_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_25_d0 <= val_fu_753_p1;
    local_input_25_we0 <= local_input_25_we0_local;

    local_input_25_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred859_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred859_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_25_we0_local <= ap_const_logic_1;
        else 
            local_input_25_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_26_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_26_ce0 <= local_input_26_ce0_local;

    local_input_26_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_26_ce0_local <= ap_const_logic_1;
        else 
            local_input_26_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_26_d0 <= val_fu_753_p1;
    local_input_26_we0 <= local_input_26_we0_local;

    local_input_26_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred847_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred847_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_26_we0_local <= ap_const_logic_1;
        else 
            local_input_26_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_27_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_27_ce0 <= local_input_27_ce0_local;

    local_input_27_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_27_ce0_local <= ap_const_logic_1;
        else 
            local_input_27_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_27_d0 <= val_fu_753_p1;
    local_input_27_we0 <= local_input_27_we0_local;

    local_input_27_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred835_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred835_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_27_we0_local <= ap_const_logic_1;
        else 
            local_input_27_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_28_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_28_ce0 <= local_input_28_ce0_local;

    local_input_28_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_28_ce0_local <= ap_const_logic_1;
        else 
            local_input_28_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_28_d0 <= val_fu_753_p1;
    local_input_28_we0 <= local_input_28_we0_local;

    local_input_28_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred823_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred823_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_28_we0_local <= ap_const_logic_1;
        else 
            local_input_28_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_29_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_29_ce0 <= local_input_29_ce0_local;

    local_input_29_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_29_ce0_local <= ap_const_logic_1;
        else 
            local_input_29_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_29_d0 <= val_fu_753_p1;
    local_input_29_we0 <= local_input_29_we0_local;

    local_input_29_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred874_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred874_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_29_we0_local <= ap_const_logic_1;
        else 
            local_input_29_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_2_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_2_ce0 <= local_input_2_ce0_local;

    local_input_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_2_ce0_local <= ap_const_logic_1;
        else 
            local_input_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_2_d0 <= val_fu_753_p1;
    local_input_2_we0 <= local_input_2_we0_local;

    local_input_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred763_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred763_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_2_we0_local <= ap_const_logic_1;
        else 
            local_input_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_3_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_3_ce0 <= local_input_3_ce0_local;

    local_input_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_3_ce0_local <= ap_const_logic_1;
        else 
            local_input_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_3_d0 <= val_fu_753_p1;
    local_input_3_we0 <= local_input_3_we0_local;

    local_input_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred751_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred751_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_3_we0_local <= ap_const_logic_1;
        else 
            local_input_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_4_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_4_ce0 <= local_input_4_ce0_local;

    local_input_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_4_ce0_local <= ap_const_logic_1;
        else 
            local_input_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_4_d0 <= val_fu_753_p1;
    local_input_4_we0 <= local_input_4_we0_local;

    local_input_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred802_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred802_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_4_we0_local <= ap_const_logic_1;
        else 
            local_input_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_5_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_5_ce0 <= local_input_5_ce0_local;

    local_input_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_5_ce0_local <= ap_const_logic_1;
        else 
            local_input_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_5_d0 <= val_fu_753_p1;
    local_input_5_we0 <= local_input_5_we0_local;

    local_input_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred723_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred723_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_5_we0_local <= ap_const_logic_1;
        else 
            local_input_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_6_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_6_ce0 <= local_input_6_ce0_local;

    local_input_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_6_ce0_local <= ap_const_logic_1;
        else 
            local_input_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_6_d0 <= val_fu_753_p1;
    local_input_6_we0 <= local_input_6_we0_local;

    local_input_6_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred711_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred711_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_6_we0_local <= ap_const_logic_1;
        else 
            local_input_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_7_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_7_ce0 <= local_input_7_ce0_local;

    local_input_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_7_ce0_local <= ap_const_logic_1;
        else 
            local_input_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_7_d0 <= val_fu_753_p1;
    local_input_7_we0 <= local_input_7_we0_local;

    local_input_7_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred699_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred699_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_7_we0_local <= ap_const_logic_1;
        else 
            local_input_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_8_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_8_ce0 <= local_input_8_ce0_local;

    local_input_8_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_8_ce0_local <= ap_const_logic_1;
        else 
            local_input_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_8_d0 <= val_fu_753_p1;
    local_input_8_we0 <= local_input_8_we0_local;

    local_input_8_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred687_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred687_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_8_we0_local <= ap_const_logic_1;
        else 
            local_input_8_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_9_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_9_ce0 <= local_input_9_ce0_local;

    local_input_9_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_9_ce0_local <= ap_const_logic_1;
        else 
            local_input_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_9_d0 <= val_fu_753_p1;
    local_input_9_we0 <= local_input_9_we0_local;

    local_input_9_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred738_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred738_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_9_we0_local <= ap_const_logic_1;
        else 
            local_input_9_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_address0 <= zext_ln62_fu_822_p1(2 - 1 downto 0);
    local_input_ce0 <= local_input_ce0_local;

    local_input_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_ce0_local <= ap_const_logic_1;
        else 
            local_input_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_input_d0 <= val_fu_753_p1;
    local_input_we0 <= local_input_we0_local;

    local_input_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_predicate_pred787_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_pred787_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_input_we0_local <= ap_const_logic_1;
        else 
            local_input_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem0_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem0_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem0_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_0_BREADY <= ap_const_logic_0;

    m_axi_gmem0_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op55_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op55_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_gmem0_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem0_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_0_WDATA <= ap_const_lv128_lc_1;
    m_axi_gmem0_0_WID <= ap_const_lv1_0;
    m_axi_gmem0_0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_0_WSTRB <= ap_const_lv16_0;
    m_axi_gmem0_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_WVALID <= ap_const_logic_0;
    mul_ln62_fu_806_p0 <= mul_ln62_fu_806_p00(5 - 1 downto 0);
    mul_ln62_fu_806_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln62_2_fu_798_p1),11));
    mul_ln62_fu_806_p1 <= ap_const_lv11_34(7 - 1 downto 0);
    select_ln59_1_fu_871_p3 <= 
        ap_const_lv7_0 when (icmp_ln59_2_fu_865_p2(0) = '1') else 
        add_ln59_2_fu_859_p2;
    select_ln59_fu_713_p3 <= 
        ap_const_lv7_0 when (icmp_ln59_1_fu_707_p2(0) = '1') else 
        add_ln59_1_fu_701_p2;
    tmp_fu_812_p4 <= mul_ln62_fu_806_p2(10 downto 8);
    trunc_ln59_fu_647_p1 <= ap_sig_allocacmp_i_1(3 - 1 downto 0);
    trunc_ln62_2_fu_798_p1 <= phi_urem_fu_156(5 - 1 downto 0);
    trunc_ln62_3_fu_676_p1 <= ap_sig_allocacmp_phi_urem45_load(3 - 1 downto 0);
    val_fu_753_p1 <= ap_phi_mux_empty_phi_fu_583_p4(16 - 1 downto 0);
    zext_ln59_fu_745_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shiftreg_fu_164),128));
    zext_ln62_fu_822_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_812_p4),64));
end behav;
