-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_3_4_ROM_AUudo is 
    generic(
             DataWidth     : integer := 11; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_3_4_ROM_AUudo is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00100100111", 1 => "00011001100", 2 => "00010100000", 3 => "11111101101", 
    4 => "11100010111", 5 => "00010011100", 6 => "00100010001", 7 => "11111000011", 
    8 => "00000011000", 9 => "00101001100", 10 => "11101001011", 11 => "00000011011", 
    12 => "11100111110", 13 => "11110111100", 14 => "11111010001", 15 => "11011111010", 
    16 => "11111100000", 17 => "00010011011", 18 => "00001011111", 19 => "11110111100", 
    20 => "00001001001", 21 => "00101101001", 22 => "00100011000", 23 => "01000100111", 
    24 => "11110111100", 25 => "00000011101", 26 => "00010100000", 27 => "00001000000", 
    28 => "11010110010", 29 => "11110110100", 30 => "00000101000", 31 => "00000011111", 
    32 => "00100110001", 33 => "00000111010", 34 => "00100001110", 35 => "11111110111", 
    36 => "00101011001", 37 => "10010001000", 38 => "11010110100", 39 => "00000100001", 
    40 => "11101111001", 41 => "00110001110", 42 => "00100000101", 43 => "11110111010", 
    44 => "00010000100", 45 => "00000100010", 46 => "11111011000", 47 => "00001010111", 
    48 => "00101101001", 49 => "00101000010", 50 => "11111001101", 51 => "11101101010", 
    52 => "00111010110", 53 => "00000000111", 54 => "11110010010", 55 => "00001111011", 
    56 => "00000101100", 57 => "11000001110", 58 => "11110011011", 59 => "00010011001", 
    60 => "11110001111", 61 => "00101110001", 62 => "00001001000", 63 => "00101001101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

