-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_0_3_ROM_AUeOg is 
    generic(
             DataWidth     : integer := 11; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_0_3_ROM_AUeOg is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11101001010", 1 => "11110011001", 2 => "11100110000", 3 => "11110010011", 
    4 => "00010101011", 5 => "11110101000", 6 => "00010001100", 7 => "11011011101", 
    8 => "00001111010", 9 => "01011000111", 10 => "11110100101", 11 => "00101101000", 
    12 => "00000100000", 13 => "11001011010", 14 => "11110111100", 15 => "11011101101", 
    16 => "00010110001", 17 => "00000000001", 18 => "00001000111", 19 => "11010100111", 
    20 => "11100111010", 21 => "11101011011", 22 => "11110111111", 23 => "11111100110", 
    24 => "00110001011", 25 => "11111000011", 26 => "00000010110", 27 => "00000101011", 
    28 => "11101011110", 29 => "10101000001", 30 => "00011010011", 31 => "00001001011", 
    32 => "11110000001", 33 => "11101100011", 34 => "00001000110", 35 => "00001110110", 
    36 => "00100011100", 37 => "11111100011", 38 => "11110011110", 39 => "00010111111", 
    40 => "11011101011", 41 => "11011100011", 42 => "11110111000", 43 => "11111001101", 
    44 => "00001000011", 45 => "00001110111", 46 => "11111100010", 47 => "00000111000", 
    48 => "00100001000", 49 => "00010111010", 50 => "11111101000", 51 => "00010010000", 
    52 => "11001011100", 53 => "00110001011", 54 => "00010110010", 55 => "11110011011", 
    56 => "00000010110", 57 => "00001000011", 58 => "00000100000", 59 => "00111111010", 
    60 => "00011100001", 61 => "11011111000", 62 => "00001111101", 63 => "11110011000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

