-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_5_0_ROM_AUAem is 
    generic(
             DataWidth     : integer := 12; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_5_0_ROM_AUAem is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "000100010010", 1 => "111100011110", 2 => "000101110111", 3 => "101110101000", 
    4 => "000001110111", 5 => "000010011111", 6 => "000001011101", 7 => "111111111111", 
    8 => "110100101111", 9 => "110110011111", 10 => "110011011001", 11 => "000000000110", 
    12 => "000010111101", 13 => "000011100110", 14 => "111111110100", 15 => "110001100010", 
    16 => "000000010011", 17 => "000011011100", 18 => "111101011001", 19 => "001000100010", 
    20 => "000011110111", 21 => "111100000110", 22 => "111100110011", 23 => "000111110100", 
    24 => "000100010111", 25 => "000111101111", 26 => "000011111100", 27 => "111111010011", 
    28 => "000010110010", 29 => "000000000100", 30 => "111100011010", 31 => "110100001101", 
    32 => "000000100001", 33 => "000011110111", 34 => "000100010111", 35 => "000000011111", 
    36 => "111001011001", 37 => "001101101010", 38 => "000101000010", 39 => "000001100011", 
    40 => "111111101001", 41 => "000011000000", 42 => "111100100111", 43 => "000000100111", 
    44 => "111001110111", 45 => "000001011010", 46 => "111111000011", 47 => "111111101001", 
    48 => "111011111110", 49 => "111001110011", 50 => "000011010100", 51 => "111101001000", 
    52 => "000110001001", 53 => "000010110100", 54 => "000110001111", 55 => "111100011010", 
    56 => "111110000001", 57 => "000100000101", 58 => "000001011111", 59 => "000001101110", 
    60 => "111110100011", 61 => "000000011110", 62 => "000011001110", 63 => "000001101111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

