-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_3_3_ROM_AUtde is 
    generic(
             DataWidth     : integer := 12; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_3_3_ROM_AUtde is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "000011000110", 1 => "000011011101", 2 => "000001100000", 3 => "111110110010", 
    4 => "000001000101", 5 => "000010100000", 6 => "000011100110", 7 => "111101000111", 
    8 => "111100101001", 9 => "110100111111", 10 => "000010100111", 11 => "111111100101", 
    12 => "000001100000", 13 => "000101100100", 14 => "111111000010", 15 => "111010111001", 
    16 => "111010001100", 17 => "000001100110", 18 => "000100110110", 19 => "111101110010", 
    20 => "111000100001", 21 => "111111000110", 22 => "000010011001", 23 => "000100000000", 
    24 => "000001111111", 25 => "000000011111", 26 => "111110110001", 27 => "000011000110", 
    28 => "111100010000", 29 => "111111100010", 30 => "111111010100", 31 => "000001110101", 
    32 => "000100100000", 33 => "000000101111", 34 => "000010110000", 35 => "111100100010", 
    36 => "001011011010", 37 => "101111110101", 38 => "111101100011", 39 => "000000111111", 
    40 => "001000110110", 41 => "110010111111", 42 => "000011100001", 43 => "111111111110", 
    44 => "111110110111", 45 => "111111101100", 46 => "111111101001", 47 => "000011000011", 
    48 => "000101000111", 49 => "111111011100", 50 => "000010011110", 51 => "110010101111", 
    52 => "110001111101", 53 => "111110101010", 54 => "111100111101", 55 => "000101010111", 
    56 => "000000000110", 57 => "111010111001", 58 => "000100111101", 59 => "000011001001", 
    60 => "111110100000", 61 => "000100011001", 62 => "000010000010", 63 => "000011010111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

