-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_4_4_ROM_AUzec is 
    generic(
             DataWidth     : integer := 12; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_4_4_ROM_AUzec is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "000011000010", 1 => "111100111000", 2 => "111100011111", 3 => "111111000110", 
    4 => "111000110110", 5 => "111111000110", 6 => "000010110110", 7 => "111110111010", 
    8 => "000000001001", 9 => "100111100100", 10 => "001000011100", 11 => "000000101011", 
    12 => "111110111000", 13 => "101011000110", 14 => "111101011011", 15 => "111111100000", 
    16 => "000010000000", 17 => "000101100000", 18 => "000001111100", 19 => "000101010010", 
    20 => "000100001101", 21 => "000000010100", 22 => "000011111110", 23 => "111010101100", 
    24 => "111100110010", 25 => "111101000011", 26 => "111101100010", 27 => "111111111101", 
    28 => "000100011011", 29 => "000000110111", 30 => "111111100010", 31 => "111010000001", 
    32 => "000010100101", 33 => "001100010100", 34 => "111100000010", 35 => "000000101101", 
    36 => "000011001110", 37 => "111110010110", 38 => "111110001000", 39 => "111101110011", 
    40 => "111100011001", 41 => "000010101101", 42 => "000010110001", 43 => "000010101011", 
    44 => "111101010110", 45 => "000011001111", 46 => "000001110111", 47 => "000001010110", 
    48 => "111101001110", 49 => "000111011101", 50 => "111100101110", 51 => "111110011101", 
    52 => "111001001101", 53 => "111100111101", 54 => "000010000011", 55 => "000010001001", 
    56 => "111110010000", 57 => "111000010010", 58 => "110110001001", 59 => "000110001101", 
    60 => "000000011011", 61 => "000001010101", 62 => "000000111100", 63 => "000000111101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

