-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_0_1_ROM_AUcud is 
    generic(
             DataWidth     : integer := 10; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_0_1_ROM_AUcud is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1011110111", 1 => "1101001111", 2 => "1011100011", 3 => "0001011101", 
    4 => "0101000100", 5 => "1111110001", 6 => "0000110001", 7 => "1011000110", 
    8 => "0010000100", 9 => "1101011010", 10 => "1101101111", 11 => "0001001011", 
    12 => "1101111100", 13 => "1100000111", 14 => "1111011100", 15 => "1101000100", 
    16 => "1110100001", 17 => "1101111010", 18 => "0000000011", 19 => "1111100100", 
    20 => "1101100101", 21 => "0000111010", 22 => "1100100111", 23 => "0110011100", 
    24 => "1101000001", 25 => "0001011000", 26 => "1110111110", 27 => "1011110100", 
    28 => "1101101110", 29 => "0100101000", 30 => "1110111101", 31 => "1110011011", 
    32 => "0011000010", 33 => "0010001101", 34 => "1111111110", 35 => "1111101111", 
    36 => "1000100111", 37 => "0001100000", 38 => "1111001110", 39 => "0010110001", 
    40 => "0000001011", 41 => "0000100010", 42 => "1110010110", 43 => "1110110100", 
    44 => "0010100111", 45 => "1011111000", 46 => "1101100010", 47 => "1101101101", 
    48 => "0011000010", 49 => "0000110010", 50 => "1110011010", 51 => "1110001101", 
    52 => "0010110101", 53 => "0011110101", 54 => "0011101000", 55 => "0010000011", 
    56 => "0001101001", 57 => "1110011100", 58 => "1100111011", 59 => "1100010101", 
    60 => "0011000001", 61 => "0101101000", 62 => "1110000001", 63 => "1110110100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

