[hls]
relative_roots=C:/Users/eswar/OneDrive/Desktop/streetfighter
# Inferred from performance & pipeline pragmas/directives
syn.directive.array_partition=street_fighter_cnn/local_input_0 dim=1 type=cyclic factor=5 variable=local_input_0
syn.directive.loop_flatten=street_fighter_cnn/CONV1_OUT  
syn.directive.loop_flatten=street_fighter_cnn/POOL1  
syn.directive.array_partition=street_fighter_cnn/pool1_out_0 dim=2 type=cyclic factor=3 variable=pool1_out_0
syn.directive.loop_flatten=street_fighter_cnn/CONV2_OUT  
syn.directive.array_partition=street_fighter_cnn/conv2_out dim=2 type=complete variable=conv2_out


