-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_CONV2_OUT_VITIS_LOOP_114_4_CONV2_B_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 13; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of street_fighter_cnn_street_fighter_cnn_Pipeline_CONV2_OUT_VITIS_LOOP_114_4_CONV2_B_ROM_AUTO_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000100110111", 1 => "0010100110001", 2 => "1110001000001", 3 => "1101110011110", 
    4 => "0001010010010", 5 => "0001011001111", 6 => "0001100100101", 7 => "0001110000111", 
    8 => "0010001010001", 9 => "0010011010101", 10 => "1010100101001", 11 => "0001101100110", 
    12 => "0001001101110", 13 => "1111011011011", 14 => "1101010111011", 15 => "0000101001100", 
    16 => "1110011001101", 17 => "0000000001001", 18 => "1111101000010", 19 => "0011000001111", 
    20 => "0010011101111", 21 => "1111100011110", 22 => "1111001100110", 23 => "0001100110000", 
    24 => "1111100000101", 25 => "0000100011101", 26 => "1100101110111", 27 => "1111000101101", 
    28 => "1110101010010", 29 => "0001110100100", 30 => "1111001010110", 31 => "1110011100101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

