// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module street_fighter_cnn_street_fighter_cnn_Pipeline_POOL1_VITIS_LOOP_91_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pool1_out_address0,
        pool1_out_ce0,
        pool1_out_we0,
        pool1_out_d0,
        pool1_out_1_address0,
        pool1_out_1_ce0,
        pool1_out_1_we0,
        pool1_out_1_d0,
        pool1_out_2_address0,
        pool1_out_2_ce0,
        pool1_out_2_we0,
        pool1_out_2_d0,
        pool1_out_3_address0,
        pool1_out_3_ce0,
        pool1_out_3_we0,
        pool1_out_3_d0,
        pool1_out_4_address0,
        pool1_out_4_ce0,
        pool1_out_4_we0,
        pool1_out_4_d0,
        pool1_out_5_address0,
        pool1_out_5_ce0,
        pool1_out_5_we0,
        pool1_out_5_d0,
        conv1_out_address0,
        conv1_out_ce0,
        conv1_out_q0,
        conv1_out_address1,
        conv1_out_ce1,
        conv1_out_q1,
        conv1_out_1_address0,
        conv1_out_1_ce0,
        conv1_out_1_q0,
        conv1_out_1_address1,
        conv1_out_1_ce1,
        conv1_out_1_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] pool1_out_address0;
output   pool1_out_ce0;
output   pool1_out_we0;
output  [14:0] pool1_out_d0;
output  [6:0] pool1_out_1_address0;
output   pool1_out_1_ce0;
output   pool1_out_1_we0;
output  [14:0] pool1_out_1_d0;
output  [6:0] pool1_out_2_address0;
output   pool1_out_2_ce0;
output   pool1_out_2_we0;
output  [14:0] pool1_out_2_d0;
output  [6:0] pool1_out_3_address0;
output   pool1_out_3_ce0;
output   pool1_out_3_we0;
output  [14:0] pool1_out_3_d0;
output  [6:0] pool1_out_4_address0;
output   pool1_out_4_ce0;
output   pool1_out_4_we0;
output  [14:0] pool1_out_4_d0;
output  [6:0] pool1_out_5_address0;
output   pool1_out_5_ce0;
output   pool1_out_5_we0;
output  [14:0] pool1_out_5_d0;
output  [9:0] conv1_out_address0;
output   conv1_out_ce0;
input  [14:0] conv1_out_q0;
output  [9:0] conv1_out_address1;
output   conv1_out_ce1;
input  [14:0] conv1_out_q1;
output  [9:0] conv1_out_1_address0;
output   conv1_out_1_ce0;
input  [14:0] conv1_out_1_q0;
output  [9:0] conv1_out_1_address1;
output   conv1_out_1_ce1;
input  [14:0] conv1_out_1_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln90_fu_245_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln91_fu_260_p2;
reg   [0:0] icmp_ln91_reg_509;
reg   [0:0] icmp_ln91_reg_509_pp0_iter1_reg;
reg   [0:0] icmp_ln91_reg_509_pp0_iter2_reg;
reg   [0:0] icmp_ln91_reg_509_pp0_iter3_reg;
reg   [0:0] icmp_ln91_reg_509_pp0_iter4_reg;
reg   [0:0] icmp_ln91_reg_509_pp0_iter5_reg;
wire   [3:0] select_ln90_fu_266_p3;
reg   [3:0] select_ln90_reg_514;
reg   [3:0] select_ln90_reg_514_pp0_iter1_reg;
reg   [3:0] select_ln90_reg_514_pp0_iter2_reg;
reg   [3:0] select_ln90_reg_514_pp0_iter3_reg;
reg   [3:0] select_ln90_reg_514_pp0_iter4_reg;
reg   [3:0] select_ln90_reg_514_pp0_iter5_reg;
wire   [0:0] trunc_ln90_fu_312_p1;
reg   [0:0] trunc_ln90_reg_522;
wire   [6:0] add_ln95_fu_379_p2;
reg   [6:0] add_ln95_reg_528;
wire   [63:0] zext_ln93_3_fu_402_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln94_1_fu_425_p1;
wire   [63:0] zext_ln95_1_fu_436_p1;
reg   [3:0] t_fu_80;
wire   [3:0] add_ln91_fu_280_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_t_load;
reg   [6:0] c_fu_84;
wire   [6:0] select_ln90_1_fu_305_p3;
reg   [9:0] indvar_flatten6_fu_88;
wire   [9:0] add_ln90_1_fu_251_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten6_load;
reg    conv1_out_ce1_local;
reg    conv1_out_ce0_local;
reg    conv1_out_1_ce1_local;
reg    conv1_out_1_ce0_local;
reg    pool1_out_1_we0_local;
wire   [1:0] trunc_ln91_fu_445_p1;
wire   [14:0] select_ln95_fu_470_p3;
reg    pool1_out_1_ce0_local;
reg    pool1_out_we0_local;
reg    pool1_out_ce0_local;
reg    pool1_out_2_we0_local;
reg    pool1_out_2_ce0_local;
reg    pool1_out_4_we0_local;
reg    pool1_out_4_ce0_local;
reg    pool1_out_3_we0_local;
reg    pool1_out_3_ce0_local;
reg    pool1_out_5_we0_local;
reg    pool1_out_5_ce0_local;
wire   [2:0] grp_fu_274_p1;
wire   [6:0] add_ln90_fu_299_p2;
wire   [4:0] lshr_ln1_fu_316_p4;
wire   [8:0] tmp_fu_326_p3;
wire   [6:0] tmp_2_fu_338_p3;
wire   [9:0] zext_ln93_fu_334_p1;
wire   [9:0] zext_ln93_1_fu_346_p1;
wire   [3:0] mul_ln91_fu_359_p0;
wire   [5:0] mul_ln91_fu_359_p1;
wire   [8:0] mul_ln91_fu_359_p2;
wire   [2:0] tmp_3_fu_365_p4;
wire   [6:0] zext_ln95_fu_375_p1;
wire   [4:0] shl_ln1_fu_385_p3;
wire   [9:0] add_ln93_1_fu_350_p2;
wire   [9:0] zext_ln93_2_fu_392_p1;
wire   [9:0] add_ln93_fu_396_p2;
wire   [4:0] or_ln1_fu_408_p3;
wire   [9:0] zext_ln94_fu_415_p1;
wire   [9:0] add_ln94_fu_419_p2;
wire   [1:0] grp_fu_274_p2;
wire   [14:0] a_fu_450_p3;
wire   [14:0] b_fu_457_p3;
wire   [0:0] icmp_ln95_fu_464_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [8:0] mul_ln91_fu_359_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 t_fu_80 = 4'd0;
#0 c_fu_84 = 7'd0;
#0 indvar_flatten6_fu_88 = 10'd0;
#0 ap_done_reg = 1'b0;
end

street_fighter_cnn_urem_4ns_3ns_2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_4ns_3ns_2_8_1_U175(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln90_fu_266_p3),
    .din1(grp_fu_274_p1),
    .ce(1'b1),
    .dout(grp_fu_274_p2)
);

street_fighter_cnn_mul_4ns_6ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_4ns_6ns_9_1_1_U176(
    .din0(mul_ln91_fu_359_p0),
    .din1(mul_ln91_fu_359_p1),
    .dout(mul_ln91_fu_359_p2)
);

street_fighter_cnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            c_fu_84 <= 7'd0;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            c_fu_84 <= select_ln90_1_fu_305_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln90_fu_245_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_88 <= add_ln90_1_fu_251_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_88 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln90_fu_245_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            t_fu_80 <= add_ln91_fu_280_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_80 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln95_reg_528 <= add_ln95_fu_379_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        icmp_ln91_reg_509_pp0_iter2_reg <= icmp_ln91_reg_509_pp0_iter1_reg;
        icmp_ln91_reg_509_pp0_iter3_reg <= icmp_ln91_reg_509_pp0_iter2_reg;
        icmp_ln91_reg_509_pp0_iter4_reg <= icmp_ln91_reg_509_pp0_iter3_reg;
        icmp_ln91_reg_509_pp0_iter5_reg <= icmp_ln91_reg_509_pp0_iter4_reg;
        select_ln90_reg_514_pp0_iter2_reg <= select_ln90_reg_514_pp0_iter1_reg;
        select_ln90_reg_514_pp0_iter3_reg <= select_ln90_reg_514_pp0_iter2_reg;
        select_ln90_reg_514_pp0_iter4_reg <= select_ln90_reg_514_pp0_iter3_reg;
        select_ln90_reg_514_pp0_iter5_reg <= select_ln90_reg_514_pp0_iter4_reg;
        trunc_ln90_reg_522 <= trunc_ln90_fu_312_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln91_reg_509 <= icmp_ln91_fu_260_p2;
        icmp_ln91_reg_509_pp0_iter1_reg <= icmp_ln91_reg_509;
        select_ln90_reg_514 <= select_ln90_fu_266_p3;
        select_ln90_reg_514_pp0_iter1_reg <= select_ln90_reg_514;
    end
end

always @ (*) begin
    if (((icmp_ln90_fu_245_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_t_load = 4'd0;
    end else begin
        ap_sig_allocacmp_t_load = t_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        conv1_out_1_ce0_local = 1'b1;
    end else begin
        conv1_out_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        conv1_out_1_ce1_local = 1'b1;
    end else begin
        conv1_out_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        conv1_out_ce0_local = 1'b1;
    end else begin
        conv1_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        conv1_out_ce1_local = 1'b1;
    end else begin
        conv1_out_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        pool1_out_1_ce0_local = 1'b1;
    end else begin
        pool1_out_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln91_fu_445_p1 == 2'd1) & (trunc_ln90_reg_522 == 1'd0))) begin
        pool1_out_1_we0_local = 1'b1;
    end else begin
        pool1_out_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        pool1_out_2_ce0_local = 1'b1;
    end else begin
        pool1_out_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln91_fu_445_p1 == 2'd0) & ~(trunc_ln91_fu_445_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln90_reg_522 == 1'd0))) begin
        pool1_out_2_we0_local = 1'b1;
    end else begin
        pool1_out_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        pool1_out_3_ce0_local = 1'b1;
    end else begin
        pool1_out_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln91_fu_445_p1 == 2'd0) & (trunc_ln90_reg_522 == 1'd1))) begin
        pool1_out_3_we0_local = 1'b1;
    end else begin
        pool1_out_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        pool1_out_4_ce0_local = 1'b1;
    end else begin
        pool1_out_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln91_fu_445_p1 == 2'd1) & (trunc_ln90_reg_522 == 1'd1))) begin
        pool1_out_4_we0_local = 1'b1;
    end else begin
        pool1_out_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        pool1_out_5_ce0_local = 1'b1;
    end else begin
        pool1_out_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln91_fu_445_p1 == 2'd0) & ~(trunc_ln91_fu_445_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln90_reg_522 == 1'd1))) begin
        pool1_out_5_we0_local = 1'b1;
    end else begin
        pool1_out_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        pool1_out_ce0_local = 1'b1;
    end else begin
        pool1_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln91_fu_445_p1 == 2'd0) & (trunc_ln90_reg_522 == 1'd0))) begin
        pool1_out_we0_local = 1'b1;
    end else begin
        pool1_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_fu_450_p3 = ((trunc_ln90_reg_522[0:0] == 1'b1) ? conv1_out_1_q1 : conv1_out_q1);

assign add_ln90_1_fu_251_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 10'd1);

assign add_ln90_fu_299_p2 = (c_fu_84 + 7'd1);

assign add_ln91_fu_280_p2 = (select_ln90_fu_266_p3 + 4'd1);

assign add_ln93_1_fu_350_p2 = (zext_ln93_fu_334_p1 + zext_ln93_1_fu_346_p1);

assign add_ln93_fu_396_p2 = (add_ln93_1_fu_350_p2 + zext_ln93_2_fu_392_p1);

assign add_ln94_fu_419_p2 = (add_ln93_1_fu_350_p2 + zext_ln94_fu_415_p1);

assign add_ln95_fu_379_p2 = (tmp_2_fu_338_p3 + zext_ln95_fu_375_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b_fu_457_p3 = ((trunc_ln90_reg_522[0:0] == 1'b1) ? conv1_out_1_q0 : conv1_out_q0);

assign conv1_out_1_address0 = zext_ln94_1_fu_425_p1;

assign conv1_out_1_address1 = zext_ln93_3_fu_402_p1;

assign conv1_out_1_ce0 = conv1_out_1_ce0_local;

assign conv1_out_1_ce1 = conv1_out_1_ce1_local;

assign conv1_out_address0 = zext_ln94_1_fu_425_p1;

assign conv1_out_address1 = zext_ln93_3_fu_402_p1;

assign conv1_out_ce0 = conv1_out_ce0_local;

assign conv1_out_ce1 = conv1_out_ce1_local;

assign grp_fu_274_p1 = 4'd3;

assign icmp_ln90_fu_245_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 10'd640) ? 1'b1 : 1'b0);

assign icmp_ln91_fu_260_p2 = ((ap_sig_allocacmp_t_load == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_464_p2 = ((a_fu_450_p3 > b_fu_457_p3) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_316_p4 = {{select_ln90_1_fu_305_p3[5:1]}};

assign mul_ln91_fu_359_p0 = mul_ln91_fu_359_p00;

assign mul_ln91_fu_359_p00 = select_ln90_reg_514_pp0_iter5_reg;

assign mul_ln91_fu_359_p1 = 9'd22;

assign or_ln1_fu_408_p3 = {{select_ln90_reg_514_pp0_iter5_reg}, {1'd1}};

assign pool1_out_1_address0 = zext_ln95_1_fu_436_p1;

assign pool1_out_1_ce0 = pool1_out_1_ce0_local;

assign pool1_out_1_d0 = select_ln95_fu_470_p3;

assign pool1_out_1_we0 = pool1_out_1_we0_local;

assign pool1_out_2_address0 = zext_ln95_1_fu_436_p1;

assign pool1_out_2_ce0 = pool1_out_2_ce0_local;

assign pool1_out_2_d0 = select_ln95_fu_470_p3;

assign pool1_out_2_we0 = pool1_out_2_we0_local;

assign pool1_out_3_address0 = zext_ln95_1_fu_436_p1;

assign pool1_out_3_ce0 = pool1_out_3_ce0_local;

assign pool1_out_3_d0 = select_ln95_fu_470_p3;

assign pool1_out_3_we0 = pool1_out_3_we0_local;

assign pool1_out_4_address0 = zext_ln95_1_fu_436_p1;

assign pool1_out_4_ce0 = pool1_out_4_ce0_local;

assign pool1_out_4_d0 = select_ln95_fu_470_p3;

assign pool1_out_4_we0 = pool1_out_4_we0_local;

assign pool1_out_5_address0 = zext_ln95_1_fu_436_p1;

assign pool1_out_5_ce0 = pool1_out_5_ce0_local;

assign pool1_out_5_d0 = select_ln95_fu_470_p3;

assign pool1_out_5_we0 = pool1_out_5_we0_local;

assign pool1_out_address0 = zext_ln95_1_fu_436_p1;

assign pool1_out_ce0 = pool1_out_ce0_local;

assign pool1_out_d0 = select_ln95_fu_470_p3;

assign pool1_out_we0 = pool1_out_we0_local;

assign select_ln90_1_fu_305_p3 = ((icmp_ln91_reg_509_pp0_iter5_reg[0:0] == 1'b1) ? add_ln90_fu_299_p2 : c_fu_84);

assign select_ln90_fu_266_p3 = ((icmp_ln91_fu_260_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_t_load);

assign select_ln95_fu_470_p3 = ((icmp_ln95_fu_464_p2[0:0] == 1'b1) ? a_fu_450_p3 : b_fu_457_p3);

assign shl_ln1_fu_385_p3 = {{select_ln90_reg_514_pp0_iter5_reg}, {1'd0}};

assign tmp_2_fu_338_p3 = {{lshr_ln1_fu_316_p4}, {2'd0}};

assign tmp_3_fu_365_p4 = {{mul_ln91_fu_359_p2[8:6]}};

assign tmp_fu_326_p3 = {{lshr_ln1_fu_316_p4}, {4'd0}};

assign trunc_ln90_fu_312_p1 = select_ln90_1_fu_305_p3[0:0];

assign trunc_ln91_fu_445_p1 = grp_fu_274_p2[1:0];

assign zext_ln93_1_fu_346_p1 = tmp_2_fu_338_p3;

assign zext_ln93_2_fu_392_p1 = shl_ln1_fu_385_p3;

assign zext_ln93_3_fu_402_p1 = add_ln93_fu_396_p2;

assign zext_ln93_fu_334_p1 = tmp_fu_326_p3;

assign zext_ln94_1_fu_425_p1 = add_ln94_fu_419_p2;

assign zext_ln94_fu_415_p1 = or_ln1_fu_408_p3;

assign zext_ln95_1_fu_436_p1 = add_ln95_reg_528;

assign zext_ln95_fu_375_p1 = tmp_3_fu_365_p4;

endmodule //street_fighter_cnn_street_fighter_cnn_Pipeline_POOL1_VITIS_LOOP_91_3
