// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module street_fighter_cnn_street_fighter_cnn_Pipeline_ARGMAX (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_0_0_080134,
        final_scores,
        final_scores_1,
        final_scores_2,
        final_scores_3,
        final_scores_4,
        final_scores_5,
        final_scores_6,
        final_scores_7,
        final_scores_8,
        best_class_out,
        best_class_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] p_0_0_080134;
input  [15:0] final_scores;
input  [15:0] final_scores_1;
input  [15:0] final_scores_2;
input  [15:0] final_scores_3;
input  [15:0] final_scores_4;
input  [15:0] final_scores_5;
input  [15:0] final_scores_6;
input  [15:0] final_scores_7;
input  [15:0] final_scores_8;
output  [31:0] best_class_out;
output   best_class_out_ap_vld;

reg ap_idle;
reg best_class_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln157_fu_165_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [15:0] max_val_fu_68;
wire   [15:0] max_val_1_fu_218_p3;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [31:0] best_class_fu_72;
wire   [31:0] best_class_1_fu_230_p3;
reg   [3:0] i_fu_76;
wire   [3:0] add_ln157_fu_238_p2;
wire    ap_block_pp0_stage0_01001;
wire   [15:0] s_fu_177_p19;
wire   [15:0] s_fu_177_p21;
wire   [0:0] icmp_ln160_fu_212_p2;
wire   [31:0] zext_ln160_fu_226_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] s_fu_177_p1;
wire   [3:0] s_fu_177_p3;
wire   [3:0] s_fu_177_p5;
wire   [3:0] s_fu_177_p7;
wire   [3:0] s_fu_177_p9;
wire   [3:0] s_fu_177_p11;
wire   [3:0] s_fu_177_p13;
wire  signed [3:0] s_fu_177_p15;
wire  signed [3:0] s_fu_177_p17;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 max_val_fu_68 = 16'd0;
#0 best_class_fu_72 = 32'd0;
#0 i_fu_76 = 4'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) street_fighter_cnn_sparsemux_19_4_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h1 ),
    .din0_WIDTH( 16 ),
    .CASE1( 4'h2 ),
    .din1_WIDTH( 16 ),
    .CASE2( 4'h3 ),
    .din2_WIDTH( 16 ),
    .CASE3( 4'h4 ),
    .din3_WIDTH( 16 ),
    .CASE4( 4'h5 ),
    .din4_WIDTH( 16 ),
    .CASE5( 4'h6 ),
    .din5_WIDTH( 16 ),
    .CASE6( 4'h7 ),
    .din6_WIDTH( 16 ),
    .CASE7( 4'h8 ),
    .din7_WIDTH( 16 ),
    .CASE8( 4'h9 ),
    .din8_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
sparsemux_19_4_16_1_1_U621(
    .din0(final_scores),
    .din1(final_scores_1),
    .din2(final_scores_2),
    .din3(final_scores_3),
    .din4(final_scores_4),
    .din5(final_scores_5),
    .din6(final_scores_6),
    .din7(final_scores_7),
    .din8(final_scores_8),
    .def(s_fu_177_p19),
    .sel(i_fu_76),
    .dout(s_fu_177_p21)
);

street_fighter_cnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            best_class_fu_72 <= 32'd0;
        end else if (((icmp_ln157_fu_165_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            best_class_fu_72 <= best_class_1_fu_230_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_76 <= 4'd1;
        end else if (((icmp_ln157_fu_165_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_76 <= add_ln157_fu_238_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            max_val_fu_68 <= p_0_0_080134;
        end else if (((icmp_ln157_fu_165_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            max_val_fu_68 <= max_val_1_fu_218_p3;
        end
    end
end

always @ (*) begin
    if (((icmp_ln157_fu_165_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln157_fu_165_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        best_class_out_ap_vld = 1'b1;
    end else begin
        best_class_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln157_fu_238_p2 = (i_fu_76 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign best_class_1_fu_230_p3 = ((icmp_ln160_fu_212_p2[0:0] == 1'b1) ? zext_ln160_fu_226_p1 : best_class_fu_72);

assign best_class_out = best_class_fu_72;

assign icmp_ln157_fu_165_p2 = ((i_fu_76 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln160_fu_212_p2 = (($signed(s_fu_177_p21) > $signed(max_val_fu_68)) ? 1'b1 : 1'b0);

assign max_val_1_fu_218_p3 = ((icmp_ln160_fu_212_p2[0:0] == 1'b1) ? s_fu_177_p21 : max_val_fu_68);

assign s_fu_177_p19 = 'bx;

assign zext_ln160_fu_226_p1 = i_fu_76;

endmodule //street_fighter_cnn_street_fighter_cnn_Pipeline_ARGMAX
