-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_CONV2_OUT_VITIS_LOOP_114_4_p_ZL7CONV2_W_41_0_ROM_cEy is 
    generic(
             DataWidth     : integer := 10; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of street_fighter_cnn_street_fighter_cnn_Pipeline_CONV2_OUT_VITIS_LOOP_114_4_p_ZL7CONV2_W_41_0_ROM_cEy is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1110011000", 1 => "1100010111", 2 => "0110000000", 3 => "0001001001", 
    4 => "1011111101", 5 => "1110111111", 6 => "1110111111", 7 => "0010010010", 
    8 => "1110001100", 9 => "0000101100", 10 => "0000010110", 11 => "1111000000", 
    12 => "0001111001", 13 => "1101000100", 14 => "0000110110", 15 => "0010010100", 
    16 => "0010000101", 17 => "0000111000", 18 => "1011100001", 19 => "1111111000", 
    20 => "1101111111", 21 => "0000010100", 22 => "1110000000", 23 => "1110100111", 
    24 => "1100100010", 25 => "1110011010", 26 => "1111101000", 27 => "0010000101", 
    28 => "0001110110", 29 => "1110010100", 30 => "1100101000", 31 => "1111000111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

