-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_CONV2_OUT_VITIS_LOOP_114_4_p_ZL7CONV2_W_1_2_ROM_AKfY is 
    generic(
             DataWidth     : integer := 10; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of street_fighter_cnn_street_fighter_cnn_Pipeline_CONV2_OUT_VITIS_LOOP_114_4_p_ZL7CONV2_W_1_2_ROM_AKfY is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1100110011", 1 => "0100000000", 2 => "1100110010", 3 => "0011011101", 
    4 => "1111000110", 5 => "1111100100", 6 => "1111100100", 7 => "1110000100", 
    8 => "0001011111", 9 => "1110101011", 10 => "0011011011", 11 => "1010000100", 
    12 => "1111011000", 13 => "0000000010", 14 => "0010011100", 15 => "0001011001", 
    16 => "1111101111", 17 => "1110100011", 18 => "0010010001", 19 => "0011010111", 
    20 => "1100101010", 21 => "1111000011", 22 => "1011111001", 23 => "0001011011", 
    24 => "0000011000", 25 => "1100101011", 26 => "1101101111", 27 => "1111111000", 
    28 => "0001010001", 29 => "1110011011", 30 => "1010000000", 31 => "0011101001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

