-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_3_2_ROM_AUsc4 is 
    generic(
             DataWidth     : integer := 12; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_3_2_ROM_AUsc4 is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "000010000100", 1 => "000001100110", 2 => "000001001011", 3 => "111110110110", 
    4 => "000011100001", 5 => "000001010011", 6 => "000001001010", 7 => "111101101111", 
    8 => "000001011000", 9 => "110100011110", 10 => "111111100111", 11 => "000000001111", 
    12 => "000100010100", 13 => "000011011010", 14 => "000000001110", 15 => "111111010110", 
    16 => "111111101111", 17 => "000010001010", 18 => "000011001010", 19 => "111111001000", 
    20 => "111100001011", 21 => "000000101111", 22 => "000010000010", 23 => "000000010110", 
    24 => "000010001101", 25 => "111101010101", 26 => "111100100010", 27 => "000010100001", 
    28 => "111110001110", 29 => "111110011111", 30 => "111110100111", 31 => "000000101101", 
    32 => "000011101010", 33 => "111111001010", 34 => "111111111001", 35 => "111011010111", 
    36 => "000011111101", 37 => "111110010001", 38 => "111101100110", 39 => "000000110011", 
    40 => "001100101111", 41 => "111000001011", 42 => "000000110100", 43 => "111111110000", 
    44 => "000001111111", 45 => "000000111110", 46 => "111110100100", 47 => "111111010110", 
    48 => "000001101000", 49 => "000010001100", 50 => "000001110111", 51 => "111101100110", 
    52 => "101110011100", 53 => "000000000100", 54 => "111110001000", 55 => "000011000011", 
    56 => "000000101111", 57 => "000001100000", 58 => "000011011111", 59 => "111011110100", 
    60 => "000000111011", 61 => "000001010011", 62 => "000001010000", 63 => "000011101100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

