-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_4_3_ROM_AUyd2 is 
    generic(
             DataWidth     : integer := 12; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_4_3_ROM_AUyd2 is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "000010100100", 1 => "000000000010", 2 => "111110100001", 3 => "000001011011", 
    4 => "111010011011", 5 => "111111110010", 6 => "000001001111", 7 => "111101010100", 
    8 => "111101011111", 9 => "011010000000", 10 => "000111111011", 11 => "000000101011", 
    12 => "000001110110", 13 => "111101001011", 14 => "111110000001", 15 => "111101011100", 
    16 => "001000111110", 17 => "000001111010", 18 => "111111111000", 19 => "000011010110", 
    20 => "000011011001", 21 => "111111011101", 22 => "000100100100", 23 => "111110011000", 
    24 => "110111100111", 25 => "111100101110", 26 => "111111100110", 27 => "111110011110", 
    28 => "000010111100", 29 => "000000001011", 30 => "000000010011", 31 => "111110011001", 
    32 => "000010001100", 33 => "000111110110", 34 => "111110001110", 35 => "111111110011", 
    36 => "001010000010", 37 => "111101010011", 38 => "000110000001", 39 => "111111100011", 
    40 => "000110011001", 41 => "000010000011", 42 => "111110011000", 43 => "000000110000", 
    44 => "000000100110", 45 => "000011011000", 46 => "000001011001", 47 => "111010000111", 
    48 => "111101110001", 49 => "000101001010", 50 => "111010111010", 51 => "111110001000", 
    52 => "110000000111", 53 => "000000111111", 54 => "111111010101", 55 => "111111101101", 
    56 => "111101111010", 57 => "110110100101", 58 => "111100111011", 59 => "000110111101", 
    60 => "111111000111", 61 => "111110101101", 62 => "000000111001", 63 => "000001101001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

