-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_CONV2_OUT_VITIS_LOOP_114_4_p_ZL7CONV2_W_16_2_ROM_btn is 
    generic(
             DataWidth     : integer := 10; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of street_fighter_cnn_street_fighter_cnn_Pipeline_CONV2_OUT_VITIS_LOOP_114_4_p_ZL7CONV2_W_16_2_ROM_btn is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000101101", 1 => "0000011010", 2 => "0000111100", 3 => "0000011110", 
    4 => "0010101001", 5 => "0111000000", 6 => "0000001110", 7 => "1110100110", 
    8 => "1111101000", 9 => "1101011111", 10 => "1111001010", 11 => "0001101111", 
    12 => "0000110010", 13 => "0000010011", 14 => "1111000000", 15 => "0001011011", 
    16 => "0010001000", 17 => "0000100111", 18 => "1110000101", 19 => "1110100011", 
    20 => "1111011001", 21 => "0000001000", 22 => "0001110000", 23 => "1101111000", 
    24 => "0010001000", 25 => "0010101101", 26 => "1100110000", 27 => "1110001000", 
    28 => "1101001111", 29 => "1011000100", 30 => "0010101100", 31 => "0001101010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

