-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_VITIS_LOOP_136_6 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sext_ln135 : IN STD_LOGIC_VECTOR (23 downto 0);
    zext_ln144 : IN STD_LOGIC_VECTOR (8 downto 0);
    conv2_out_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    conv2_out_ce0 : OUT STD_LOGIC;
    conv2_out_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    conv2_out_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    conv2_out_1_ce0 : OUT STD_LOGIC;
    conv2_out_1_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    conv2_out_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    conv2_out_2_ce0 : OUT STD_LOGIC;
    conv2_out_2_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    conv2_out_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    conv2_out_3_ce0 : OUT STD_LOGIC;
    conv2_out_3_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    conv2_out_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    conv2_out_4_ce0 : OUT STD_LOGIC;
    conv2_out_4_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    conv2_out_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    conv2_out_5_ce0 : OUT STD_LOGIC;
    conv2_out_5_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    conv2_out_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    conv2_out_6_ce0 : OUT STD_LOGIC;
    conv2_out_6_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    conv2_out_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    conv2_out_7_ce0 : OUT STD_LOGIC;
    conv2_out_7_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    conv2_out_8_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    conv2_out_8_ce0 : OUT STD_LOGIC;
    conv2_out_8_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    conv2_out_9_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    conv2_out_9_ce0 : OUT STD_LOGIC;
    conv2_out_9_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    i_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    dbg_gap0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    dbg_gap0_ap_vld : OUT STD_LOGIC;
    final_scores_9_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    final_scores_9_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of street_fighter_cnn_street_fighter_cnn_Pipeline_VITIS_LOOP_136_6 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv82_33333333334 : STD_LOGIC_VECTOR (81 downto 0) := "0000000000000000000000000000000000000000110011001100110011001100110011001100110100";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv32_43 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000011";
    constant ap_const_lv32_51 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010001";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln136_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal FC_W_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal FC_W_q0 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal j_1_reg_661 : STD_LOGIC_VECTOR (5 downto 0);
    signal j_1_reg_661_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln136_reg_666 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln136_reg_666_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln145_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln145_reg_720 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln145_reg_720_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln141_fu_509_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln141_reg_724 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_fu_540_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_reg_734 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln136_fu_338_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln144_3_fu_523_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal final_scores_9_fu_108 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal score_fu_112 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sext_ln135_cast_fu_304_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_fu_116 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln136_fu_332_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_j_1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal conv2_out_ce0_local : STD_LOGIC;
    signal conv2_out_1_ce0_local : STD_LOGIC;
    signal conv2_out_2_ce0_local : STD_LOGIC;
    signal conv2_out_3_ce0_local : STD_LOGIC;
    signal conv2_out_4_ce0_local : STD_LOGIC;
    signal conv2_out_5_ce0_local : STD_LOGIC;
    signal conv2_out_6_ce0_local : STD_LOGIC;
    signal conv2_out_7_ce0_local : STD_LOGIC;
    signal conv2_out_8_ce0_local : STD_LOGIC;
    signal conv2_out_9_ce0_local : STD_LOGIC;
    signal FC_W_ce0_local : STD_LOGIC;
    signal mul_ln144_fu_295_p0 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln143_fu_299_p0 : STD_LOGIC_VECTOR (40 downto 0);
    signal mul_ln143_fu_299_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal trunc_ln145_fu_352_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_362_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln145_fu_356_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln_fu_370_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal conv2_out_1_load_cast_fu_393_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal conv2_out_load_cast_fu_389_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln141_1_fu_429_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal conv2_out_3_load_cast_fu_401_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal conv2_out_4_load_cast_fu_405_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln141_2_fu_439_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln141_2_fu_445_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal conv2_out_2_load_cast_fu_397_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln141_3_fu_449_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln141_3_fu_455_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln141_1_fu_435_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln141_4_fu_459_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal conv2_out_5_load_cast_fu_409_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal conv2_out_6_load_cast_fu_413_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln141_5_fu_469_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal conv2_out_8_load_cast_fu_421_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln141_fu_425_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln141_6_fu_479_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln141_6_fu_485_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal conv2_out_7_load_cast_fu_417_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln141_7_fu_489_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln141_7_fu_495_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln141_5_fu_475_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln141_8_fu_499_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln141_8_fu_505_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln141_4_fu_465_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln144_2_fu_515_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln144_1_fu_518_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln3_fu_528_p3 : STD_LOGIC_VECTOR (40 downto 0);
    signal mul_ln143_fu_299_p2 : STD_LOGIC_VECTOR (81 downto 0);
    signal shl_ln4_fu_558_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal shl_ln144_1_fu_565_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln144_fu_295_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal shl_ln144_2_fu_583_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal sext_ln144_1_fu_591_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal add_ln144_fu_595_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln143_fu_299_p00 : STD_LOGIC_VECTOR (81 downto 0);
    signal mul_ln144_fu_295_p00 : STD_LOGIC_VECTOR (51 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component street_fighter_cnn_mul_27ns_25s_52_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (26 downto 0);
        din1 : IN STD_LOGIC_VECTOR (24 downto 0);
        dout : OUT STD_LOGIC_VECTOR (51 downto 0) );
    end component;


    component street_fighter_cnn_mul_41ns_43ns_82_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (40 downto 0);
        din1 : IN STD_LOGIC_VECTOR (42 downto 0);
        dout : OUT STD_LOGIC_VECTOR (81 downto 0) );
    end component;


    component street_fighter_cnn_street_fighter_cnn_Pipeline_VITIS_LOOP_136_6_FC_W_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component street_fighter_cnn_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    FC_W_U : component street_fighter_cnn_street_fighter_cnn_Pipeline_VITIS_LOOP_136_6_FC_W_ROM_AUTO_1R
    generic map (
        DataWidth => 13,
        AddressRange => 320,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => FC_W_address0,
        ce0 => FC_W_ce0_local,
        q0 => FC_W_q0);

    mul_27ns_25s_52_1_1_U601 : component street_fighter_cnn_mul_27ns_25s_52_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 27,
        din1_WIDTH => 25,
        dout_WIDTH => 52)
    port map (
        din0 => mul_ln144_fu_295_p0,
        din1 => shl_ln144_1_fu_565_p3,
        dout => mul_ln144_fu_295_p2);

    mul_41ns_43ns_82_1_1_U602 : component street_fighter_cnn_mul_41ns_43ns_82_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 41,
        din1_WIDTH => 43,
        dout_WIDTH => 82)
    port map (
        din0 => mul_ln143_fu_299_p0,
        din1 => mul_ln143_fu_299_p1,
        dout => mul_ln143_fu_299_p2);

    flow_control_loop_pipe_sequential_init_U : component street_fighter_cnn_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    final_scores_9_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    final_scores_9_fu_108 <= ap_const_lv16_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    final_scores_9_fu_108 <= add_ln144_fu_595_p2(49 downto 34);
                end if;
            end if; 
        end if;
    end process;

    j_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln136_fu_326_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_116 <= add_ln136_fu_332_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_116 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    score_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    score_fu_112 <= sext_ln135_cast_fu_304_p1;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    score_fu_112 <= add_ln144_fu_595_p2(53 downto 22);
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln141_reg_724 <= add_ln141_fu_509_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln136_reg_666 <= icmp_ln136_fu_326_p2;
                icmp_ln136_reg_666_pp0_iter1_reg <= icmp_ln136_reg_666;
                icmp_ln145_reg_720 <= icmp_ln145_fu_378_p2;
                icmp_ln145_reg_720_pp0_iter1_reg <= icmp_ln145_reg_720;
                j_1_reg_661 <= ap_sig_allocacmp_j_1;
                j_1_reg_661_pp0_iter1_reg <= j_1_reg_661;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                tmp_reg_734 <= mul_ln143_fu_299_p2(81 downto 67);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    FC_W_address0 <= zext_ln144_3_fu_523_p1(9 - 1 downto 0);

    FC_W_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            FC_W_ce0_local <= ap_const_logic_1;
        else 
            FC_W_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln136_fu_332_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_1) + unsigned(ap_const_lv6_1));
    add_ln141_1_fu_429_p2 <= std_logic_vector(unsigned(conv2_out_1_load_cast_fu_393_p1) + unsigned(conv2_out_load_cast_fu_389_p1));
    add_ln141_2_fu_439_p2 <= std_logic_vector(unsigned(conv2_out_3_load_cast_fu_401_p1) + unsigned(conv2_out_4_load_cast_fu_405_p1));
    add_ln141_3_fu_449_p2 <= std_logic_vector(unsigned(zext_ln141_2_fu_445_p1) + unsigned(conv2_out_2_load_cast_fu_397_p1));
    add_ln141_4_fu_459_p2 <= std_logic_vector(unsigned(zext_ln141_3_fu_455_p1) + unsigned(zext_ln141_1_fu_435_p1));
    add_ln141_5_fu_469_p2 <= std_logic_vector(unsigned(conv2_out_5_load_cast_fu_409_p1) + unsigned(conv2_out_6_load_cast_fu_413_p1));
    add_ln141_6_fu_479_p2 <= std_logic_vector(unsigned(conv2_out_8_load_cast_fu_421_p1) + unsigned(zext_ln141_fu_425_p1));
    add_ln141_7_fu_489_p2 <= std_logic_vector(unsigned(zext_ln141_6_fu_485_p1) + unsigned(conv2_out_7_load_cast_fu_417_p1));
    add_ln141_8_fu_499_p2 <= std_logic_vector(unsigned(zext_ln141_7_fu_495_p1) + unsigned(zext_ln141_5_fu_475_p1));
    add_ln141_fu_509_p2 <= std_logic_vector(unsigned(zext_ln141_8_fu_505_p1) + unsigned(zext_ln141_4_fu_465_p1));
    add_ln144_1_fu_518_p2 <= std_logic_vector(unsigned(zext_ln144) + unsigned(zext_ln144_2_fu_515_p1));
    add_ln144_fu_595_p2 <= std_logic_vector(unsigned(shl_ln144_2_fu_583_p3) + unsigned(sext_ln144_1_fu_591_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln136_fu_326_p2)
    begin
        if (((icmp_ln136_fu_326_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter2_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, j_fu_116)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j_1 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_j_1 <= j_fu_116;
        end if; 
    end process;

    conv2_out_1_address0 <= zext_ln136_fu_338_p1(5 - 1 downto 0);
    conv2_out_1_ce0 <= conv2_out_1_ce0_local;

    conv2_out_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv2_out_1_ce0_local <= ap_const_logic_1;
        else 
            conv2_out_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_1_load_cast_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(conv2_out_1_q0),16));
    conv2_out_2_address0 <= zext_ln136_fu_338_p1(5 - 1 downto 0);
    conv2_out_2_ce0 <= conv2_out_2_ce0_local;

    conv2_out_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv2_out_2_ce0_local <= ap_const_logic_1;
        else 
            conv2_out_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_2_load_cast_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(conv2_out_2_q0),17));
    conv2_out_3_address0 <= zext_ln136_fu_338_p1(5 - 1 downto 0);
    conv2_out_3_ce0 <= conv2_out_3_ce0_local;

    conv2_out_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv2_out_3_ce0_local <= ap_const_logic_1;
        else 
            conv2_out_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_3_load_cast_fu_401_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(conv2_out_3_q0),16));
    conv2_out_4_address0 <= zext_ln136_fu_338_p1(5 - 1 downto 0);
    conv2_out_4_ce0 <= conv2_out_4_ce0_local;

    conv2_out_4_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv2_out_4_ce0_local <= ap_const_logic_1;
        else 
            conv2_out_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_4_load_cast_fu_405_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(conv2_out_4_q0),16));
    conv2_out_5_address0 <= zext_ln136_fu_338_p1(5 - 1 downto 0);
    conv2_out_5_ce0 <= conv2_out_5_ce0_local;

    conv2_out_5_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv2_out_5_ce0_local <= ap_const_logic_1;
        else 
            conv2_out_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_5_load_cast_fu_409_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(conv2_out_5_q0),16));
    conv2_out_6_address0 <= zext_ln136_fu_338_p1(5 - 1 downto 0);
    conv2_out_6_ce0 <= conv2_out_6_ce0_local;

    conv2_out_6_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv2_out_6_ce0_local <= ap_const_logic_1;
        else 
            conv2_out_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_6_load_cast_fu_413_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(conv2_out_6_q0),16));
    conv2_out_7_address0 <= zext_ln136_fu_338_p1(5 - 1 downto 0);
    conv2_out_7_ce0 <= conv2_out_7_ce0_local;

    conv2_out_7_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv2_out_7_ce0_local <= ap_const_logic_1;
        else 
            conv2_out_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_7_load_cast_fu_417_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(conv2_out_7_q0),17));
    conv2_out_8_address0 <= zext_ln136_fu_338_p1(5 - 1 downto 0);
    conv2_out_8_ce0 <= conv2_out_8_ce0_local;

    conv2_out_8_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv2_out_8_ce0_local <= ap_const_logic_1;
        else 
            conv2_out_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_8_load_cast_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(conv2_out_8_q0),16));
    conv2_out_9_address0 <= zext_ln136_fu_338_p1(5 - 1 downto 0);
    conv2_out_9_ce0 <= conv2_out_9_ce0_local;

    conv2_out_9_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv2_out_9_ce0_local <= ap_const_logic_1;
        else 
            conv2_out_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_address0 <= zext_ln136_fu_338_p1(5 - 1 downto 0);
    conv2_out_ce0 <= conv2_out_ce0_local;

    conv2_out_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv2_out_ce0_local <= ap_const_logic_1;
        else 
            conv2_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_load_cast_fu_389_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(conv2_out_q0),16));
    dbg_gap0 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_540_p4),16));

    dbg_gap0_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln145_reg_720_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln145_reg_720_pp0_iter1_reg = ap_const_lv1_1))) then 
            dbg_gap0_ap_vld <= ap_const_logic_1;
        else 
            dbg_gap0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    final_scores_9_out <= final_scores_9_fu_108;

    final_scores_9_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln136_reg_666_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (icmp_ln136_reg_666_pp0_iter1_reg = ap_const_lv1_1))) then 
            final_scores_9_out_ap_vld <= ap_const_logic_1;
        else 
            final_scores_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln136_fu_326_p2 <= "1" when (ap_sig_allocacmp_j_1 = ap_const_lv6_20) else "0";
    icmp_ln145_fu_378_p2 <= "1" when (or_ln_fu_370_p3 = ap_const_lv5_0) else "0";
    mul_ln143_fu_299_p0 <= mul_ln143_fu_299_p00(41 - 1 downto 0);
    mul_ln143_fu_299_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln3_fu_528_p3),82));
    mul_ln143_fu_299_p1 <= ap_const_lv82_33333333334(43 - 1 downto 0);
    mul_ln144_fu_295_p0 <= mul_ln144_fu_295_p00(27 - 1 downto 0);
    mul_ln144_fu_295_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln4_fu_558_p3),52));
    or_ln145_fu_356_p2 <= (trunc_ln145_fu_352_p1 or i_1);
    or_ln_fu_370_p3 <= (tmp_1_fu_362_p3 & or_ln145_fu_356_p2);
        sext_ln135_cast_fu_304_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln135),32));

        sext_ln144_1_fu_591_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln144_fu_295_p2),54));

    shl_ln144_1_fu_565_p3 <= (FC_W_q0 & ap_const_lv12_0);
    shl_ln144_2_fu_583_p3 <= (score_fu_112 & ap_const_lv22_0);
    shl_ln3_fu_528_p3 <= (add_ln141_reg_724 & ap_const_lv22_0);
    shl_ln4_fu_558_p3 <= (tmp_reg_734 & ap_const_lv12_0);
    tmp_1_fu_362_p3 <= ap_sig_allocacmp_j_1(4 downto 4);
    tmp_fu_540_p4 <= mul_ln143_fu_299_p2(81 downto 67);
    trunc_ln145_fu_352_p1 <= ap_sig_allocacmp_j_1(4 - 1 downto 0);
    zext_ln136_fu_338_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_j_1),64));
    zext_ln141_1_fu_435_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln141_1_fu_429_p2),18));
    zext_ln141_2_fu_445_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln141_2_fu_439_p2),17));
    zext_ln141_3_fu_455_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln141_3_fu_449_p2),18));
    zext_ln141_4_fu_465_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln141_4_fu_459_p2),19));
    zext_ln141_5_fu_475_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln141_5_fu_469_p2),18));
    zext_ln141_6_fu_485_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln141_6_fu_479_p2),17));
    zext_ln141_7_fu_495_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln141_7_fu_489_p2),18));
    zext_ln141_8_fu_505_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln141_8_fu_499_p2),19));
    zext_ln141_fu_425_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(conv2_out_9_q0),16));
    zext_ln144_2_fu_515_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_1_reg_661_pp0_iter1_reg),9));
    zext_ln144_3_fu_523_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln144_1_fu_518_p2),64));
end behav;
