-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_CONV2_OUT_VITIS_LOOP_114_4_p_ZL7CONV2_W_12_2_ROM_bhl is 
    generic(
             DataWidth     : integer := 10; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of street_fighter_cnn_street_fighter_cnn_Pipeline_CONV2_OUT_VITIS_LOOP_114_4_p_ZL7CONV2_W_12_2_ROM_bhl is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1100111101", 1 => "0000001110", 2 => "1100000100", 3 => "0011011101", 
    4 => "1101101100", 5 => "0011101001", 6 => "0001010010", 7 => "0010100110", 
    8 => "1111100101", 9 => "0000100001", 10 => "0011000010", 11 => "1110110010", 
    12 => "0000011111", 13 => "0000011010", 14 => "0100110100", 15 => "0011001000", 
    16 => "0110010110", 17 => "0000101101", 18 => "0001011110", 19 => "0000100001", 
    20 => "0000010100", 21 => "1011101100", 22 => "1111011101", 23 => "1110111011", 
    24 => "1101011111", 25 => "0010111111", 26 => "1111101000", 27 => "0001111010", 
    28 => "1111111110", 29 => "0001011011", 30 => "0001101001", 31 => "1111100010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

