-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_5_1_ROM_AUBew is 
    generic(
             DataWidth     : integer := 11; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_5_1_ROM_AUBew is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00000010001", 1 => "11101110001", 2 => "00011111111", 3 => "11100010110", 
    4 => "00000101100", 5 => "00010111100", 6 => "11111110111", 7 => "11111000110", 
    8 => "11011010101", 9 => "11000001001", 10 => "11010110101", 11 => "11111100100", 
    12 => "00000010010", 13 => "11011101000", 14 => "11111000010", 15 => "10110100100", 
    16 => "11101001010", 17 => "11110011000", 18 => "11110011101", 19 => "00001110000", 
    20 => "11111010010", 21 => "11110010010", 22 => "00001000110", 23 => "00111010000", 
    24 => "11101001111", 25 => "00101001011", 26 => "00000100001", 27 => "11110111010", 
    28 => "00001000011", 29 => "11011111001", 30 => "11111110110", 31 => "10111101001", 
    32 => "00001110011", 33 => "11101101101", 34 => "00011101110", 35 => "11110111101", 
    36 => "11010011101", 37 => "01100011111", 38 => "00010001100", 39 => "00001010111", 
    40 => "11101100100", 41 => "00001010010", 42 => "11110110100", 43 => "00001000010", 
    44 => "11101101100", 45 => "00100010100", 46 => "11100101001", 47 => "00010111100", 
    48 => "11101110100", 49 => "11100001110", 50 => "00001001101", 51 => "11110100000", 
    52 => "00100101010", 53 => "00010001001", 54 => "00010100110", 55 => "11101001110", 
    56 => "11111100100", 57 => "00001101101", 58 => "11111111100", 59 => "00101101010", 
    60 => "11110010001", 61 => "11100100010", 62 => "00000110110", 63 => "11111001011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

