-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_1_1_ROM_AUhbi is 
    generic(
             DataWidth     : integer := 11; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_1_1_ROM_AUhbi is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00001010101", 1 => "11100100110", 2 => "00001011101", 3 => "00110001000", 
    4 => "00000001100", 5 => "11111101110", 6 => "00011000001", 7 => "00001011000", 
    8 => "11101000101", 9 => "00010000011", 10 => "11011111110", 11 => "00001101000", 
    12 => "11100010000", 13 => "01010101010", 14 => "11111010010", 15 => "00000010110", 
    16 => "00000010110", 17 => "11111101111", 18 => "00001010010", 19 => "00000111001", 
    20 => "00000010101", 21 => "11001111101", 22 => "00000100100", 23 => "11100001101", 
    24 => "11110000111", 25 => "11100101101", 26 => "11100010001", 27 => "11111110001", 
    28 => "11110000111", 29 => "11010100000", 30 => "11101011000", 31 => "00010111101", 
    32 => "00001000110", 33 => "00110000101", 34 => "11110111111", 35 => "00001001010", 
    36 => "11111101011", 37 => "11111101011", 38 => "00001110001", 39 => "00001010101", 
    40 => "11111111101", 41 => "11110100000", 42 => "00011011001", 43 => "11111000111", 
    44 => "00000111001", 45 => "11111100110", 46 => "00011011011", 47 => "11100011100", 
    48 => "11101110010", 49 => "00000100000", 50 => "11111100101", 51 => "00000010011", 
    52 => "01001010010", 53 => "00011101001", 54 => "11101000111", 55 => "11110110010", 
    56 => "11111101001", 57 => "11110110010", 58 => "00000101011", 59 => "11110001000", 
    60 => "11111011100", 61 => "11111110011", 62 => "01000101010", 63 => "00001101000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

