-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_POOL1_VITIS_LOOP_91_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    pool1_out_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    pool1_out_ce0 : OUT STD_LOGIC;
    pool1_out_we0 : OUT STD_LOGIC;
    pool1_out_d0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    pool1_out_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    pool1_out_1_ce0 : OUT STD_LOGIC;
    pool1_out_1_we0 : OUT STD_LOGIC;
    pool1_out_1_d0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    pool1_out_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    pool1_out_2_ce0 : OUT STD_LOGIC;
    pool1_out_2_we0 : OUT STD_LOGIC;
    pool1_out_2_d0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    pool1_out_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    pool1_out_3_ce0 : OUT STD_LOGIC;
    pool1_out_3_we0 : OUT STD_LOGIC;
    pool1_out_3_d0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    pool1_out_4_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    pool1_out_4_ce0 : OUT STD_LOGIC;
    pool1_out_4_we0 : OUT STD_LOGIC;
    pool1_out_4_d0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    pool1_out_5_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    pool1_out_5_ce0 : OUT STD_LOGIC;
    pool1_out_5_we0 : OUT STD_LOGIC;
    pool1_out_5_d0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    conv1_out_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    conv1_out_ce0 : OUT STD_LOGIC;
    conv1_out_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    conv1_out_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    conv1_out_ce1 : OUT STD_LOGIC;
    conv1_out_q1 : IN STD_LOGIC_VECTOR (14 downto 0);
    conv1_out_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    conv1_out_1_ce0 : OUT STD_LOGIC;
    conv1_out_1_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    conv1_out_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    conv1_out_1_ce1 : OUT STD_LOGIC;
    conv1_out_1_q1 : IN STD_LOGIC_VECTOR (14 downto 0) );
end;


architecture behav of street_fighter_cnn_street_fighter_cnn_Pipeline_POOL1_VITIS_LOOP_91_3 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv10_280 : STD_LOGIC_VECTOR (9 downto 0) := "1010000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv9_16 : STD_LOGIC_VECTOR (8 downto 0) := "000010110";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln90_fu_245_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln91_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_reg_509 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_reg_509_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_reg_509_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_reg_509_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_reg_509_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_reg_509_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln90_fu_266_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln90_reg_514 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln90_reg_514_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln90_reg_514_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln90_reg_514_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln90_reg_514_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln90_reg_514_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln90_fu_312_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln90_reg_522 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln95_fu_379_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln95_reg_528 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln93_3_fu_402_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln94_1_fu_425_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln95_1_fu_436_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal t_fu_80 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln91_fu_280_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_t_load : STD_LOGIC_VECTOR (3 downto 0);
    signal c_fu_84 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal select_ln90_1_fu_305_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten6_fu_88 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln90_1_fu_251_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten6_load : STD_LOGIC_VECTOR (9 downto 0);
    signal conv1_out_ce1_local : STD_LOGIC;
    signal conv1_out_ce0_local : STD_LOGIC;
    signal conv1_out_1_ce1_local : STD_LOGIC;
    signal conv1_out_1_ce0_local : STD_LOGIC;
    signal pool1_out_1_we0_local : STD_LOGIC;
    signal trunc_ln91_fu_445_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln95_fu_470_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal pool1_out_1_ce0_local : STD_LOGIC;
    signal pool1_out_we0_local : STD_LOGIC;
    signal pool1_out_ce0_local : STD_LOGIC;
    signal pool1_out_2_we0_local : STD_LOGIC;
    signal pool1_out_2_ce0_local : STD_LOGIC;
    signal pool1_out_4_we0_local : STD_LOGIC;
    signal pool1_out_4_ce0_local : STD_LOGIC;
    signal pool1_out_3_we0_local : STD_LOGIC;
    signal pool1_out_3_ce0_local : STD_LOGIC;
    signal pool1_out_5_we0_local : STD_LOGIC;
    signal pool1_out_5_ce0_local : STD_LOGIC;
    signal grp_fu_274_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln90_fu_299_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal lshr_ln1_fu_316_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_326_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_fu_338_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln93_fu_334_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln93_1_fu_346_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln91_fu_359_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln91_fu_359_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln91_fu_359_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_3_fu_365_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln95_fu_375_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln1_fu_385_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln93_1_fu_350_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln93_2_fu_392_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln93_fu_396_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln1_fu_408_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln94_fu_415_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln94_fu_419_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_274_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal a_fu_450_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal b_fu_457_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln95_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln91_fu_359_p00 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component street_fighter_cnn_urem_4ns_3ns_2_8_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component street_fighter_cnn_mul_4ns_6ns_9_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component street_fighter_cnn_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    urem_4ns_3ns_2_8_1_U175 : component street_fighter_cnn_urem_4ns_3ns_2_8_1
    generic map (
        ID => 1,
        NUM_STAGE => 8,
        din0_WIDTH => 4,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln90_fu_266_p3,
        din1 => grp_fu_274_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_274_p2);

    mul_4ns_6ns_9_1_1_U176 : component street_fighter_cnn_mul_4ns_6ns_9_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 6,
        dout_WIDTH => 9)
    port map (
        din0 => mul_ln91_fu_359_p0,
        din1 => mul_ln91_fu_359_p1,
        dout => mul_ln91_fu_359_p2);

    flow_control_loop_pipe_sequential_init_U : component street_fighter_cnn_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    c_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    c_fu_84 <= ap_const_lv7_0;
                elsif ((ap_enable_reg_pp0_iter6 = ap_const_logic_1)) then 
                    c_fu_84 <= select_ln90_1_fu_305_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten6_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln90_fu_245_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten6_fu_88 <= add_ln90_1_fu_251_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten6_fu_88 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    t_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln90_fu_245_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    t_fu_80 <= add_ln91_fu_280_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    t_fu_80 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln95_reg_528 <= add_ln95_fu_379_p2;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                icmp_ln91_reg_509_pp0_iter2_reg <= icmp_ln91_reg_509_pp0_iter1_reg;
                icmp_ln91_reg_509_pp0_iter3_reg <= icmp_ln91_reg_509_pp0_iter2_reg;
                icmp_ln91_reg_509_pp0_iter4_reg <= icmp_ln91_reg_509_pp0_iter3_reg;
                icmp_ln91_reg_509_pp0_iter5_reg <= icmp_ln91_reg_509_pp0_iter4_reg;
                select_ln90_reg_514_pp0_iter2_reg <= select_ln90_reg_514_pp0_iter1_reg;
                select_ln90_reg_514_pp0_iter3_reg <= select_ln90_reg_514_pp0_iter2_reg;
                select_ln90_reg_514_pp0_iter4_reg <= select_ln90_reg_514_pp0_iter3_reg;
                select_ln90_reg_514_pp0_iter5_reg <= select_ln90_reg_514_pp0_iter4_reg;
                trunc_ln90_reg_522 <= trunc_ln90_fu_312_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln91_reg_509 <= icmp_ln91_fu_260_p2;
                icmp_ln91_reg_509_pp0_iter1_reg <= icmp_ln91_reg_509;
                select_ln90_reg_514 <= select_ln90_fu_266_p3;
                select_ln90_reg_514_pp0_iter1_reg <= select_ln90_reg_514;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    a_fu_450_p3 <= 
        conv1_out_1_q1 when (trunc_ln90_reg_522(0) = '1') else 
        conv1_out_q1;
    add_ln90_1_fu_251_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten6_load) + unsigned(ap_const_lv10_1));
    add_ln90_fu_299_p2 <= std_logic_vector(unsigned(c_fu_84) + unsigned(ap_const_lv7_1));
    add_ln91_fu_280_p2 <= std_logic_vector(unsigned(select_ln90_fu_266_p3) + unsigned(ap_const_lv4_1));
    add_ln93_1_fu_350_p2 <= std_logic_vector(unsigned(zext_ln93_fu_334_p1) + unsigned(zext_ln93_1_fu_346_p1));
    add_ln93_fu_396_p2 <= std_logic_vector(unsigned(add_ln93_1_fu_350_p2) + unsigned(zext_ln93_2_fu_392_p1));
    add_ln94_fu_419_p2 <= std_logic_vector(unsigned(add_ln93_1_fu_350_p2) + unsigned(zext_ln94_fu_415_p1));
    add_ln95_fu_379_p2 <= std_logic_vector(unsigned(tmp_2_fu_338_p3) + unsigned(zext_ln95_fu_375_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln90_fu_245_p2)
    begin
        if (((icmp_ln90_fu_245_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter6_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten6_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten6_fu_88)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten6_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten6_load <= indvar_flatten6_fu_88;
        end if; 
    end process;


    ap_sig_allocacmp_t_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, t_fu_80, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_t_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_t_load <= t_fu_80;
        end if; 
    end process;

    b_fu_457_p3 <= 
        conv1_out_1_q0 when (trunc_ln90_reg_522(0) = '1') else 
        conv1_out_q0;
    conv1_out_1_address0 <= zext_ln94_1_fu_425_p1(10 - 1 downto 0);
    conv1_out_1_address1 <= zext_ln93_3_fu_402_p1(10 - 1 downto 0);
    conv1_out_1_ce0 <= conv1_out_1_ce0_local;

    conv1_out_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            conv1_out_1_ce0_local <= ap_const_logic_1;
        else 
            conv1_out_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv1_out_1_ce1 <= conv1_out_1_ce1_local;

    conv1_out_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            conv1_out_1_ce1_local <= ap_const_logic_1;
        else 
            conv1_out_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    conv1_out_address0 <= zext_ln94_1_fu_425_p1(10 - 1 downto 0);
    conv1_out_address1 <= zext_ln93_3_fu_402_p1(10 - 1 downto 0);
    conv1_out_ce0 <= conv1_out_ce0_local;

    conv1_out_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            conv1_out_ce0_local <= ap_const_logic_1;
        else 
            conv1_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv1_out_ce1 <= conv1_out_ce1_local;

    conv1_out_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            conv1_out_ce1_local <= ap_const_logic_1;
        else 
            conv1_out_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_274_p1 <= ap_const_lv4_3(3 - 1 downto 0);
    icmp_ln90_fu_245_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten6_load = ap_const_lv10_280) else "0";
    icmp_ln91_fu_260_p2 <= "1" when (ap_sig_allocacmp_t_load = ap_const_lv4_A) else "0";
    icmp_ln95_fu_464_p2 <= "1" when (unsigned(a_fu_450_p3) > unsigned(b_fu_457_p3)) else "0";
    lshr_ln1_fu_316_p4 <= select_ln90_1_fu_305_p3(5 downto 1);
    mul_ln91_fu_359_p0 <= mul_ln91_fu_359_p00(4 - 1 downto 0);
    mul_ln91_fu_359_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln90_reg_514_pp0_iter5_reg),9));
    mul_ln91_fu_359_p1 <= ap_const_lv9_16(6 - 1 downto 0);
    or_ln1_fu_408_p3 <= (select_ln90_reg_514_pp0_iter5_reg & ap_const_lv1_1);
    pool1_out_1_address0 <= zext_ln95_1_fu_436_p1(7 - 1 downto 0);
    pool1_out_1_ce0 <= pool1_out_1_ce0_local;

    pool1_out_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            pool1_out_1_ce0_local <= ap_const_logic_1;
        else 
            pool1_out_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pool1_out_1_d0 <= select_ln95_fu_470_p3;
    pool1_out_1_we0 <= pool1_out_1_we0_local;

    pool1_out_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001, trunc_ln90_reg_522, trunc_ln91_fu_445_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (trunc_ln91_fu_445_p1 = ap_const_lv2_1) and (trunc_ln90_reg_522 = ap_const_lv1_0))) then 
            pool1_out_1_we0_local <= ap_const_logic_1;
        else 
            pool1_out_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    pool1_out_2_address0 <= zext_ln95_1_fu_436_p1(7 - 1 downto 0);
    pool1_out_2_ce0 <= pool1_out_2_ce0_local;

    pool1_out_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            pool1_out_2_ce0_local <= ap_const_logic_1;
        else 
            pool1_out_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pool1_out_2_d0 <= select_ln95_fu_470_p3;
    pool1_out_2_we0 <= pool1_out_2_we0_local;

    pool1_out_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001, trunc_ln90_reg_522, trunc_ln91_fu_445_p1)
    begin
        if ((not((trunc_ln91_fu_445_p1 = ap_const_lv2_0)) and not((trunc_ln91_fu_445_p1 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (trunc_ln90_reg_522 = ap_const_lv1_0))) then 
            pool1_out_2_we0_local <= ap_const_logic_1;
        else 
            pool1_out_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    pool1_out_3_address0 <= zext_ln95_1_fu_436_p1(7 - 1 downto 0);
    pool1_out_3_ce0 <= pool1_out_3_ce0_local;

    pool1_out_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            pool1_out_3_ce0_local <= ap_const_logic_1;
        else 
            pool1_out_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pool1_out_3_d0 <= select_ln95_fu_470_p3;
    pool1_out_3_we0 <= pool1_out_3_we0_local;

    pool1_out_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001, trunc_ln90_reg_522, trunc_ln91_fu_445_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (trunc_ln91_fu_445_p1 = ap_const_lv2_0) and (trunc_ln90_reg_522 = ap_const_lv1_1))) then 
            pool1_out_3_we0_local <= ap_const_logic_1;
        else 
            pool1_out_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    pool1_out_4_address0 <= zext_ln95_1_fu_436_p1(7 - 1 downto 0);
    pool1_out_4_ce0 <= pool1_out_4_ce0_local;

    pool1_out_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            pool1_out_4_ce0_local <= ap_const_logic_1;
        else 
            pool1_out_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pool1_out_4_d0 <= select_ln95_fu_470_p3;
    pool1_out_4_we0 <= pool1_out_4_we0_local;

    pool1_out_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001, trunc_ln90_reg_522, trunc_ln91_fu_445_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (trunc_ln91_fu_445_p1 = ap_const_lv2_1) and (trunc_ln90_reg_522 = ap_const_lv1_1))) then 
            pool1_out_4_we0_local <= ap_const_logic_1;
        else 
            pool1_out_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    pool1_out_5_address0 <= zext_ln95_1_fu_436_p1(7 - 1 downto 0);
    pool1_out_5_ce0 <= pool1_out_5_ce0_local;

    pool1_out_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            pool1_out_5_ce0_local <= ap_const_logic_1;
        else 
            pool1_out_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pool1_out_5_d0 <= select_ln95_fu_470_p3;
    pool1_out_5_we0 <= pool1_out_5_we0_local;

    pool1_out_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001, trunc_ln90_reg_522, trunc_ln91_fu_445_p1)
    begin
        if ((not((trunc_ln91_fu_445_p1 = ap_const_lv2_0)) and not((trunc_ln91_fu_445_p1 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (trunc_ln90_reg_522 = ap_const_lv1_1))) then 
            pool1_out_5_we0_local <= ap_const_logic_1;
        else 
            pool1_out_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    pool1_out_address0 <= zext_ln95_1_fu_436_p1(7 - 1 downto 0);
    pool1_out_ce0 <= pool1_out_ce0_local;

    pool1_out_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            pool1_out_ce0_local <= ap_const_logic_1;
        else 
            pool1_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pool1_out_d0 <= select_ln95_fu_470_p3;
    pool1_out_we0 <= pool1_out_we0_local;

    pool1_out_we0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001, trunc_ln90_reg_522, trunc_ln91_fu_445_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (trunc_ln91_fu_445_p1 = ap_const_lv2_0) and (trunc_ln90_reg_522 = ap_const_lv1_0))) then 
            pool1_out_we0_local <= ap_const_logic_1;
        else 
            pool1_out_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln90_1_fu_305_p3 <= 
        add_ln90_fu_299_p2 when (icmp_ln91_reg_509_pp0_iter5_reg(0) = '1') else 
        c_fu_84;
    select_ln90_fu_266_p3 <= 
        ap_const_lv4_0 when (icmp_ln91_fu_260_p2(0) = '1') else 
        ap_sig_allocacmp_t_load;
    select_ln95_fu_470_p3 <= 
        a_fu_450_p3 when (icmp_ln95_fu_464_p2(0) = '1') else 
        b_fu_457_p3;
    shl_ln1_fu_385_p3 <= (select_ln90_reg_514_pp0_iter5_reg & ap_const_lv1_0);
    tmp_2_fu_338_p3 <= (lshr_ln1_fu_316_p4 & ap_const_lv2_0);
    tmp_3_fu_365_p4 <= mul_ln91_fu_359_p2(8 downto 6);
    tmp_fu_326_p3 <= (lshr_ln1_fu_316_p4 & ap_const_lv4_0);
    trunc_ln90_fu_312_p1 <= select_ln90_1_fu_305_p3(1 - 1 downto 0);
    trunc_ln91_fu_445_p1 <= grp_fu_274_p2(2 - 1 downto 0);
    zext_ln93_1_fu_346_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_338_p3),10));
    zext_ln93_2_fu_392_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_385_p3),10));
    zext_ln93_3_fu_402_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln93_fu_396_p2),64));
    zext_ln93_fu_334_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_326_p3),10));
    zext_ln94_1_fu_425_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln94_fu_419_p2),64));
    zext_ln94_fu_415_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln1_fu_408_p3),10));
    zext_ln95_1_fu_436_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln95_reg_528),64));
    zext_ln95_fu_375_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_365_p4),7));
end behav;
