-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_1_2_ROM_AUibs is 
    generic(
             DataWidth     : integer := 11; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_1_2_ROM_AUibs is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00000000100", 1 => "11011111100", 2 => "00011001100", 3 => "10001111011", 
    4 => "00000100100", 5 => "00000000100", 6 => "11111111000", 7 => "11111000011", 
    8 => "11101010010", 9 => "00011000100", 10 => "11101000000", 11 => "00001001100", 
    12 => "11011101111", 13 => "10100011000", 14 => "11101110111", 15 => "00001101011", 
    16 => "00100000010", 17 => "11111100000", 18 => "00100000111", 19 => "00000110010", 
    20 => "00011001100", 21 => "00100101000", 22 => "11111000100", 23 => "11011101100", 
    24 => "01000000010", 25 => "00011001000", 26 => "11011011111", 27 => "00000000111", 
    28 => "11110111100", 29 => "11010010111", 30 => "00000100001", 31 => "00111010100", 
    32 => "11110000001", 33 => "00111001110", 34 => "11110000010", 35 => "00000101110", 
    36 => "11101100110", 37 => "11111111000", 38 => "11110111110", 39 => "00000110000", 
    40 => "11011010010", 41 => "00010101000", 42 => "00000010010", 43 => "11110110110", 
    44 => "11100100011", 45 => "11111111100", 46 => "00000101101", 47 => "11110001101", 
    48 => "11100100100", 49 => "00001111111", 50 => "11110000010", 51 => "11110001010", 
    52 => "00100110110", 53 => "11110010011", 54 => "11100010100", 55 => "11110111011", 
    56 => "00011001111", 57 => "11110000010", 58 => "11111101110", 59 => "11100001010", 
    60 => "11101000111", 61 => "00001001001", 62 => "00101111111", 63 => "00000010100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

