-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_2_3_ROM_AUocq is 
    generic(
             DataWidth     : integer := 12; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_2_3_ROM_AUocq is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "000011001000", 1 => "111001001101", 2 => "000000111011", 3 => "000000111100", 
    4 => "111111011011", 5 => "000000001010", 6 => "111111011101", 7 => "000010110010", 
    8 => "000100000110", 9 => "111101011010", 10 => "000101010001", 11 => "000011010000", 
    12 => "000010100000", 13 => "010001011100", 14 => "000010101110", 15 => "000010010111", 
    16 => "111001001001", 17 => "000100101011", 18 => "000100111011", 19 => "111110011011", 
    20 => "111011001010", 21 => "111011111111", 22 => "000110011101", 23 => "111110000001", 
    24 => "110111011001", 25 => "111010010001", 26 => "111111110111", 27 => "000001000010", 
    28 => "111110000101", 29 => "111110001110", 30 => "111110010001", 31 => "001010101101", 
    32 => "111011100110", 33 => "001000011000", 34 => "111110010010", 35 => "000000000000", 
    36 => "111111011100", 37 => "000010110101", 38 => "000101110011", 39 => "000000001110", 
    40 => "111110110100", 41 => "111101110100", 42 => "000001101111", 43 => "000010000010", 
    44 => "000010110000", 45 => "111111010101", 46 => "000011101000", 47 => "111110101000", 
    48 => "000000011101", 49 => "000011011101", 50 => "000100000111", 51 => "000000001111", 
    52 => "111111001001", 53 => "000011101000", 54 => "111101110111", 55 => "111010111001", 
    56 => "000100111011", 57 => "111110101100", 58 => "000110111100", 59 => "111101000111", 
    60 => "000100110010", 61 => "000000010001", 62 => "000000110000", 63 => "111101110000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

