-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_2_1_ROM_AUmb6 is 
    generic(
             DataWidth     : integer := 11; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of street_fighter_cnn_street_fighter_cnn_Pipeline_CONV1_OUT_VITIS_LOOP_72_1_p_ZL7CONV1_W_2_1_ROM_AUmb6 is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00000011000", 1 => "11100111111", 2 => "11110011110", 3 => "00000100001", 
    4 => "00011110001", 5 => "00001001010", 6 => "11111000001", 7 => "11110010010", 
    8 => "11100100100", 9 => "01100111000", 10 => "00011010010", 11 => "00000011111", 
    12 => "11110101101", 13 => "10101110010", 14 => "00001111010", 15 => "00011001010", 
    16 => "11011010011", 17 => "00011100000", 18 => "00001010100", 19 => "00001000011", 
    20 => "00001110101", 21 => "00001101111", 22 => "11101101001", 23 => "11101101001", 
    24 => "00110001001", 25 => "00000100001", 26 => "11110001010", 27 => "11101101000", 
    28 => "00010000001", 29 => "00000011111", 30 => "11011111011", 31 => "10101101100", 
    32 => "11111001011", 33 => "00011111101", 34 => "11110110000", 35 => "11110110001", 
    36 => "11110111010", 37 => "00010000111", 38 => "11110000001", 39 => "11111110100", 
    40 => "11011010100", 41 => "00001001000", 42 => "11010111010", 43 => "11111100101", 
    44 => "11111000100", 45 => "11111010011", 46 => "00000001000", 47 => "00101001001", 
    48 => "11011101101", 49 => "00000101110", 50 => "00010111101", 51 => "11110100100", 
    52 => "00011100000", 53 => "11110110111", 54 => "00010010111", 55 => "11110010010", 
    56 => "00001110101", 57 => "11100101000", 58 => "11101100110", 59 => "00001010010", 
    60 => "00001111101", 61 => "00001111101", 62 => "00001001110", 63 => "11111001011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

